# Objetivo_4

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
from scipy.stats import chi2_contingency
import altair as alt
import plotly.graph_objects as go
import warnings

warnings.simplefilter(action='ignore', category=FutureWarning)

In [2]:
df = pd.read_excel('datos_CAIMEDvXI.xlsx')

In [4]:
edad_intervals = [0, 49, 59, 79, 150]
edad_labels = ['<50', '50-59', '60-79', '>80']

df['edad_grupo'] = pd.cut(
    df['edad_calculada'], bins=edad_intervals, labels=edad_labels, right=False
)

In [10]:
agrupaciones =['edad_calculada',
 'sexo',
 'tipo_de_afiliacion',
 'estrato_socieconomico',
 'antecedentes_de_tabaquismo',
 'ACV'] + [
 'Enfermedad  relevante',
 'ACV',
 'Riesgo CV']
variables = ['colesterol_total_controlado']

+ ['cLDL_controlado',
       'HDL_controlado',
       'Trigliceridos_controlados']

In [16]:
import pandas as pd
from scipy.stats import chi2_contingency
import plotly.graph_objects as go

# Definir intervalos y etiquetas para agrupar edades
edad_intervals = [0, 49, 59, 79, 150]
edad_labels = ['<50', '50-59', '60-79', '>80']
variables_categoricas = ['edad_grupo', 'sexo']+['Hipolipemiante']+ ['cLDL_controlado',
                                                                    'estrato_socieconomico',
 'antecedentes_de_tabaquismo',
 '¿resultados_relacionados_a_problemas cardiacos?',
       'HDL_controlado',
       'Trigliceridos_controlados']
variables_numericas = ['edad_calculada'] 
df['edad_grupo'] = pd.cut(
    df['edad_calculada'], bins=edad_intervals, labels=edad_labels, right=False
)

for variable in variables:
    for agrupacion in agrupaciones:
        if agrupacion == 'edad_calculada':
            tabla_frecuencias = pd.crosstab(
                df['edad_grupo'], df[variable], margins=False
            )
        else:
            tabla_frecuencias = pd.crosstab(
                df[agrupacion], df[variable], margins=False
            )
        
        # Agregar una columna con el total por fila
        tabla_frecuencias["Total"] = tabla_frecuencias.sum(axis=1)
        
        # Calcular porcentajes por fila
        totales_fila = tabla_frecuencias["Total"]
        porcentajes = (tabla_frecuencias.div(totales_fila, axis=0) * 100).round(2)
        
        # Crear tabla final con valores y porcentajes
        tabla_final_percent = tabla_frecuencias.astype(str) + " (" + porcentajes.astype(str) + "%)"
        
        # Ajustar el formato de la esquina del título
        titulo_esquina = f"{agrupacion}/{variable}"
        
        # Realizar análisis Chi-cuadrado para variables categóricas
        if agrupacion in variables_categoricas and variable in variables_categoricas:
            print(agrupacion, variable)
            
            if tabla_frecuencias.shape[0] > 1 and tabla_frecuencias.shape[1] > 1:
                try:
                    chi2, p, dof, expected = chi2_contingency(tabla_frecuencias.iloc[:, :-1])
                    print(f"Chi-cuadrado entre {agrupacion} y {variable}:")
                    print(f"  Estadístico Chi2: {chi2:.2f}")
                    print(f"  p-valor: {p:.4f}")
                    print(f"  Grados de libertad: {dof}")
                except ValueError:
                    print(f"No se puede calcular Chi-cuadrado entre {agrupacion} y {variable}: tabla inválida.")
            else:
                print(f"La tabla de contingencia para {agrupacion} y {variable} no tiene suficientes datos.")
        
        # Mostrar la tabla de frecuencias y porcentajes
        print(tabla_final_percent)
        display(tabla_final_percent)

colesterol_total_controlado    controlado no controlado         Total
edad_grupo
<50                           33 (71.74%)   13 (28.26%)   46 (100.0%)
50-59                        105 (72.41%)   40 (27.59%)  145 (100.0%)
60-79                        483 (75.47%)  157 (24.53%)  640 (100.0%)
>80                          104 (85.25%)   18 (14.75%)  122 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
edad_grupo
<50                           33 (71.74%)   13 (28.26%)   46 (100.0%)
50-59                        105 (72.41%)   40 (27.59%)  145 (100.0%)
60-79                        483 (75.47%)  157 (24.53%)  640 (100.0%)
>80                          104 (85.25%)   18 (14.75%)  122 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
sexo
femenino                     221 (66.77%)  110 (33.23%)  331 (100.0%)
masculino                    504 (81.03%)  118 (18.97%)  622 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
sexo
femenino                     221 (66.77%)  110 (33.23%)  331 (100.0%)
masculino                    504 (81.03%)  118 (18.97%)  622 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
tipo_de_afiliacion
contributivo                 334 (78.04%)   94 (21.96%)  428 (100.0%)
otro                           1 (100.0%)      0 (0.0%)    1 (100.0%)
polizas de seguro              1 (100.0%)      0 (0.0%)    1 (100.0%)
prepagada                      1 (100.0%)      0 (0.0%)    1 (100.0%)
regimen especial              44 (77.19%)   13 (22.81%)   57 (100.0%)
subsidiado                   344 (73.98%)  121 (26.02%)  465 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
tipo_de_afiliacion
contributivo                 334 (78.04%)   94 (21.96%)  428 (100.0%)
otro                           1 (100.0%)      0 (0.0%)    1 (100.0%)
polizas de seguro              1 (100.0%)      0 (0.0%)    1 (100.0%)
prepagada                      1 (100.0%)      0 (0.0%)    1 (100.0%)
regimen especial              44 (77.19%)   13 (22.81%)   57 (100.0%)
subsidiado                   344 (73.98%)  121 (26.02%)  465 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
estrato_socieconomico
1                            133 (74.72%)   45 (25.28%)  178 (100.0%)
2                            315 (77.02%)   94 (22.98%)  409 (100.0%)
3                            200 (72.99%)   74 (27.01%)  274 (100.0%)
4                             63 (82.89%)   13 (17.11%)   76 (100.0%)
5                             10 (100.0%)      0 (0.0%)   10 (100.0%)
6                              4 (66.67%)    2 (33.33%)    6 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
estrato_socieconomico
1                            133 (74.72%)   45 (25.28%)  178 (100.0%)
2                            315 (77.02%)   94 (22.98%)  409 (100.0%)
3                            200 (72.99%)   74 (27.01%)  274 (100.0%)
4                             63 (82.89%)   13 (17.11%)   76 (100.0%)
5                             10 (100.0%)      0 (0.0%)   10 (100.0%)
6                              4 (66.67%)    2 (33.33%)    6 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
antecedentes_de_tabaquismo
no                           457 (72.89%)  170 (27.11%)  627 (100.0%)
si                           268 (82.21%)   58 (17.79%)  326 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
antecedentes_de_tabaquismo
no                           457 (72.89%)  170 (27.11%)  627 (100.0%)
si                           268 (82.21%)   58 (17.79%)  326 (100.0%)

colesterol_total_controlado                        controlado no controlado  \
¿resultados_relacionados_a_problemas cardiacos?
no                                               699 (75.57%)  226 (24.43%)
si                                                 26 (96.3%)      1 (3.7%)

colesterol_total_controlado                             Total
¿resultados_relacionados_a_problemas cardiacos?
no                                               925 (100.0%)
si                                                27 (100.0%)

colesterol_total_controlado,controlado,no controlado,Total
¿resultados_relacionados_a_problemas cardiacos?,,,
no,699 (75.57%),226 (24.43%),925 (100.0%)
si,26 (96.3%),1 (3.7%),27 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
ACV
No                           645 (75.44%)  210 (24.56%)  855 (100.0%)
Si                            80 (81.63%)   18 (18.37%)   98 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
ACV
No                           645 (75.44%)  210 (24.56%)  855 (100.0%)
Si                            80 (81.63%)   18 (18.37%)   98 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
Riesgo CV
Alto                           21 (75.0%)     7 (25.0%)   28 (100.0%)
Muy alto                     704 (76.11%)  221 (23.89%)  925 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
Riesgo CV
Alto                           21 (75.0%)     7 (25.0%)   28 (100.0%)
Muy alto                     704 (76.11%)  221 (23.89%)  925 (100.0%)

In [8]:
import pandas as pd
import plotly.graph_objects as go

# Definición de intervalos
hb1a_interv = {'POC_hba1c(%)': [0, 5.7, 6.4, 7.5, 10, max(df['POC_hba1c(%)']) + 4]}
pres_sist = {'masculino': [0, 120, 130, 139, max(df['presion_arterial_sistolica'])],
             'femenino': [0, 120, 130, 139, max(df['presion_arterial_sistolica'])]}
IMC_interv = {'IMC': [0, 19.9, 24.9, 29.9, 40, max(df['IMC']) + 1]}
per_inter = {'masculino': [0, 94, 102, max(df['perimetro_abdominal'])],
             'femenino': [0, 80, 88, max(df['perimetro_abdominal'])]}
pres_diast = {'masculino': [0, 80, 90, 120, max(df['presion_arterial_diastolica'])],
              'femenino': [0, 80, 90, 120, max(df['presion_arterial_diastolica'])]}

# Creación de intervalos en el DataFrame
df['POC_hba1c_intervalo'] = pd.cut(df['POC_hba1c(%)'], bins=hb1a_interv['POC_hba1c(%)']).astype(str)
df['IMC_intervalo'] = pd.cut(df['IMC'], bins=IMC_interv['IMC']).astype(str)
df['perimetro_abdominal_intervalo'] = pd.cut(df['perimetro_abdominal'], bins=per_inter['masculino']).astype(str)
df['presion_arterial_sistolica_intervalo'] = pd.cut(df['presion_arterial_sistolica'], bins=pres_sist['masculino']).astype(str)
df['presion_arterial_diastolica_intervalo'] = pd.cut(df['presion_arterial_diastolica'], bins=pres_diast['masculino']).astype(str)
variables = ['IMC_intervalo', 'POC_hba1c_intervalo', 'perimetro_abdominal_intervalo', 
             'presion_arterial_sistolica_intervalo', 'presion_arterial_diastolica_intervalo']

for variable in variables:
    for agrupacion in agrupaciones:
        # Crear tabla de frecuencias cruzadas
        tabla_frecuencias = pd.crosstab(df[agrupacion], df[variable])

        # Calcular totales por columna
        totales_columna = tabla_frecuencias.sum(axis=0)

        # Calcular porcentajes por columna correctamente
        porcentajes = tabla_frecuencias.div(totales_columna, axis=1) * 100

        # Agregar columna de totales para las filas
        tabla_frecuencias['Total'] = tabla_frecuencias.sum(axis=1)

        # Calcular porcentaje en la columna "Total" basado en el total global
        porcentajes['Total'] = (tabla_frecuencias['Total'] / tabla_frecuencias['Total'].sum() * 100).round(2)

        # Agregar fila de totales (valores absolutos y porcentaje 100%)
        tabla_frecuencias.loc['Total'] = tabla_frecuencias.sum(axis=0)
        porcentajes.loc['Total'] = [100.0] * len(tabla_frecuencias.columns)

        # Combinar frecuencias y porcentajes en formato "valor (porcentaje%)"
        tabla_final_percent = tabla_frecuencias.astype(str) + " (" + porcentajes.round(2).astype(str) + "%)"
        if 'nan' in list(tabla_final_percent.columns):
            tabla_final_percent =  tabla_final_percent.drop('nan',axis='columns')

        print(tabla_final_percent)
        fig = go.Figure(data=[go.Table(
            header=dict(
                values=['Categoría'] + list(tabla_final_percent.columns),
                fill_color='paleturquoise',
                align='center'
            ),
            cells=dict(
                values=[tabla_final_percent.index] + [tabla_final_percent[col].values for col in tabla_final_percent.columns],
                fill_color='lavender',
                align='center'
            )
        )])

        # Título dinámico de la tabla
        fig.update_layout(
            title=f'Tabla de Frecuencias: {agrupacion} vs {variable}'
        )
        fig.show()

IMC_intervalo   (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  (29.9, 40.0]  \
edad_calculada
25                 0 (0.0%)     1 (0.31%)      0 (0.0%)      0 (0.0%)
31                 0 (0.0%)      0 (0.0%)      0 (0.0%)     1 (0.54%)
33                 0 (0.0%)      0 (0.0%)     1 (0.25%)      0 (0.0%)
34                 0 (0.0%)     1 (0.31%)      0 (0.0%)      0 (0.0%)
35                 0 (0.0%)      0 (0.0%)     1 (0.25%)      0 (0.0%)
...                     ...           ...           ...           ...
90                 0 (0.0%)     1 (0.31%)      0 (0.0%)      0 (0.0%)
91                 0 (0.0%)     2 (0.63%)     1 (0.25%)      0 (0.0%)
92                 0 (0.0%)     1 (0.31%)      0 (0.0%)      0 (0.0%)
93                 0 (0.0%)     1 (0.31%)      0 (0.0%)      0 (0.0%)
Total           41 (100.0%)  319 (100.0%)  401 (100.0%)  185 (100.0%)

IMC_intervalo  (40.0, 50.66]         Total
edad_calculada
25                  0 (0.0%)      1 (0.1%)
31                  0 (0.0%)      1 (0.1%)
33                  0 (0.0%)      1 (0.1%)
34                  0 (0.0%)      1 (0.1%)
35                  0 (0.0%)      1 (0.1%)
...                      ...           ...
90                  0 (0.0%)      1 (0.1%)
91                  0 (0.0%)     3 (0.31%)
92                  0 (0.0%)      1 (0.1%)
93                  0 (0.0%)      1 (0.1%)
Total             6 (100.0%)  953 (100.0%)

[62 rows x 6 columns]

IMC_intervalo  (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  (29.9, 40.0]  \
sexo
femenino       20 (48.78%)   104 (32.6%)  113 (28.18%)   91 (49.19%)
masculino      21 (51.22%)   215 (67.4%)  288 (71.82%)   94 (50.81%)
Total          41 (100.0%)  319 (100.0%)  401 (100.0%)  185 (100.0%)

IMC_intervalo (40.0, 50.66]         Total
sexo
femenino         2 (33.33%)  331 (34.73%)
masculino        4 (66.67%)  622 (65.27%)
Total            6 (100.0%)  953 (100.0%)

IMC_intervalo       (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  (29.9, 40.0]  \
tipo_de_afiliacion
contributivo        13 (31.71%)  142 (44.51%)  183 (45.64%)   86 (46.49%)
otro                   0 (0.0%)      0 (0.0%)     1 (0.25%)      0 (0.0%)
polizas de seguro     1 (2.44%)      0 (0.0%)      0 (0.0%)      0 (0.0%)
prepagada              0 (0.0%)      0 (0.0%)     1 (0.25%)      0 (0.0%)
regimen especial      2 (4.88%)    18 (5.64%)    23 (5.74%)    14 (7.57%)
subsidiado          25 (60.98%)  159 (49.84%)  193 (48.13%)   85 (45.95%)
Total               41 (100.0%)  319 (100.0%)  401 (100.0%)  185 (100.0%)

IMC_intervalo      (40.0, 50.66]         Total
tipo_de_afiliacion
contributivo           3 (50.0%)  428 (44.91%)
otro                    0 (0.0%)      1 (0.1%)
polizas de seguro       0 (0.0%)      1 (0.1%)
prepagada               0 (0.0%)      1 (0.1%)
regimen especial        0 (0.0%)    57 (5.98%)
subsidiado             3 (50.0%)  465 (48.79%)
Total                 6 (100.0%)  953 (100.0%)

IMC_intervalo          (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  (29.9, 40.0]  \
estrato_socieconomico
1                      12 (29.27%)   57 (17.87%)   66 (16.46%)   41 (22.16%)
2                      15 (36.59%)   126 (39.5%)  175 (43.64%)   89 (48.11%)
3                      13 (31.71%)   97 (30.41%)  120 (29.93%)   43 (23.24%)
4                        1 (2.44%)    31 (9.72%)    32 (7.98%)    12 (6.49%)
5                         0 (0.0%)     7 (2.19%)     3 (0.75%)      0 (0.0%)
6                         0 (0.0%)     1 (0.31%)     5 (1.25%)      0 (0.0%)
Total                  41 (100.0%)  319 (100.0%)  401 (100.0%)  185 (100.0%)

IMC_intervalo         (40.0, 50.66]         Total
estrato_socieconomico
1                        2 (33.33%)  178 (18.68%)
2                         3 (50.0%)  409 (42.92%)
3                        1 (16.67%)  274 (28.75%)
4                          0 (0.0%)    76 (7.97%)
5                          0 (0.0%)    10 (1.05%)
6                          0 (0.0%)     6 (0.63%)
Total                    6 (100.0%)  953 (100.0%)

IMC_intervalo               (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  \
antecedentes_de_tabaquismo
no                          22 (53.66%)  213 (66.77%)  260 (64.84%)
si                          19 (46.34%)  106 (33.23%)  141 (35.16%)
Total                       41 (100.0%)  319 (100.0%)  401 (100.0%)

IMC_intervalo               (29.9, 40.0] (40.0, 50.66]         Total
antecedentes_de_tabaquismo
no                          126 (68.11%)    5 (83.33%)  627 (65.79%)
si                           59 (31.89%)    1 (16.67%)  326 (34.21%)
Total                       185 (100.0%)    6 (100.0%)  953 (100.0%)

IMC_intervalo                                    (0.0, 19.9]  (19.9, 24.9]  \
¿resultados_relacionados_a_problemas cardiacos?
no                                               41 (100.0%)  311 (97.49%)
si                                                  0 (0.0%)     8 (2.51%)
Total                                            41 (100.0%)  319 (100.0%)

IMC_intervalo                                    (24.9, 29.9]  (29.9, 40.0]  \
¿resultados_relacionados_a_problemas cardiacos?
no                                               386 (96.26%)  181 (97.84%)
si                                                 15 (3.74%)     4 (2.16%)
Total                                            401 (100.0%)  185 (100.0%)

IMC_intervalo                                   (40.0, 50.66]         Total
¿resultados_relacionados_a_problemas cardiacos?
no                                                 6 (100.0%)  925 (97.16%)
si                                                   0 (0.0%)    27 (2.84%)
Total                                              6 (100.0%)  952 (100.0%)

IMC_intervalo  (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  (29.9, 40.0]  \
ACV
No             37 (90.24%)  286 (89.66%)  356 (88.78%)  169 (91.35%)
Si               4 (9.76%)   33 (10.34%)   45 (11.22%)    16 (8.65%)
Total          41 (100.0%)  319 (100.0%)  401 (100.0%)  185 (100.0%)

IMC_intervalo (40.0, 50.66]         Total
ACV
No               6 (100.0%)  855 (89.72%)
Si                 0 (0.0%)   98 (10.28%)
Total            6 (100.0%)  953 (100.0%)

IMC_intervalo  (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  (29.9, 40.0]  \
Diabetico
No             29 (70.73%)  227 (72.29%)  289 (72.61%)   127 (69.4%)
Si             12 (29.27%)   87 (27.71%)  109 (27.39%)    56 (30.6%)
Total          41 (100.0%)  314 (100.0%)  398 (100.0%)  183 (100.0%)

IMC_intervalo (40.0, 50.66]         Total
Diabetico
No               6 (100.0%)   679 (72.0%)
Si                 0 (0.0%)   264 (28.0%)
Total            6 (100.0%)  943 (100.0%)

IMC_intervalo                                       (0.0, 19.9] (19.9, 24.9]  \
Tiempo de DM
Entre 10 y 20 años                                   3 (27.27%)  34 (40.48%)
Mas de 20 años/ Compromiso de órganos por la di...     0 (0.0%)    6 (7.14%)
Menos de 10 años                                     8 (72.73%)  44 (52.38%)
Total                                               11 (100.0%)  84 (100.0%)

IMC_intervalo                                       (24.9, 29.9] (29.9, 40.0]  \
Tiempo de DM
Entre 10 y 20 años                                   39 (37.14%)  19 (37.25%)
Mas de 20 años/ Compromiso de órganos por la di...     9 (8.57%)   6 (11.76%)
Menos de 10 años                                     57 (54.29%)  26 (50.98%)
Total                                               105 (100.0%)  51 (100.0%)

IMC_intervalo                                              Total
Tiempo de DM
Entre 10 y 20 años                                   95 (37.85%)
Mas de 20 años/ Compromiso de órganos por la di...    21 (8.37%)
Menos de 10 años                                    135 (53.78%)
Total                                               251 (100.0%)

IMC_intervalo  (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  (29.9, 40.0]  \
Hipertensión
No             11 (26.83%)   91 (28.98%)  109 (27.53%)   37 (20.22%)
Si             30 (73.17%)  223 (71.02%)  287 (72.47%)  146 (79.78%)
Total          41 (100.0%)  314 (100.0%)  396 (100.0%)  183 (100.0%)

IMC_intervalo (40.0, 50.66]         Total
Hipertensión
No               1 (16.67%)  249 (26.46%)
Si               5 (83.33%)  692 (73.54%)
Total            6 (100.0%)  941 (100.0%)

IMC_intervalo                 (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  \
Hipercolesterolemia familiar
No                            26 (63.41%)   211 (67.2%)  262 (65.99%)
Si                            15 (36.59%)   103 (32.8%)  135 (34.01%)
Total                         41 (100.0%)  314 (100.0%)  397 (100.0%)

IMC_intervalo                 (29.9, 40.0] (40.0, 50.66]         Total
Hipercolesterolemia familiar
No                            130 (71.04%)    6 (100.0%)  636 (67.52%)
Si                             53 (28.96%)      0 (0.0%)  306 (32.48%)
Total                         183 (100.0%)    6 (100.0%)  942 (100.0%)

IMC_intervalo  (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  (29.9, 40.0]  \
ERCoDialisis
No             37 (90.24%)  299 (95.22%)  381 (95.97%)  181 (98.91%)
Si               4 (9.76%)    15 (4.78%)    16 (4.03%)     2 (1.09%)
Total          41 (100.0%)  314 (100.0%)  397 (100.0%)  183 (100.0%)

IMC_intervalo (40.0, 50.66]         Total
ERCoDialisis
No               6 (100.0%)  905 (96.07%)
Si                 0 (0.0%)    37 (3.93%)
Total            6 (100.0%)  942 (100.0%)

IMC_intervalo                     (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  \
Ultimo Rango de Colesterol total
Desconocido                        36 (87.8%)  276 (88.46%)  318 (80.92%)
Menor o igual a 309                  0 (0.0%)      0 (0.0%)      0 (0.0%)
NA                                  5 (12.2%)   33 (10.58%)   66 (16.79%)
≤309mg/dL                            0 (0.0%)     3 (0.96%)     8 (2.04%)
≥310mg/dL                            0 (0.0%)      0 (0.0%)     1 (0.25%)
Total                             41 (100.0%)  312 (100.0%)  393 (100.0%)

IMC_intervalo                     (29.9, 40.0] (40.0, 50.66]         Total
Ultimo Rango de Colesterol total
Desconocido                       136 (75.14%)     3 (50.0%)  770 (82.44%)
Menor o igual a 309                  1 (0.55%)      0 (0.0%)     1 (0.11%)
NA                                 41 (22.65%)     3 (50.0%)  148 (15.85%)
≤309mg/dL                            3 (1.66%)      0 (0.0%)     14 (1.5%)
≥310mg/dL                             0 (0.0%)      0 (0.0%)     1 (0.11%)
Total                             181 (100.0%)    6 (100.0%)  934 (100.0%)

IMC_intervalo          (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  (29.9, 40.0]  \
Enfermedad  relevante
No                        0 (0.0%)    10 (3.18%)     9 (2.26%)     4 (2.19%)
Si                     41 (100.0%)  304 (96.82%)  389 (97.74%)  179 (97.81%)
Total                  41 (100.0%)  314 (100.0%)  398 (100.0%)  183 (100.0%)

IMC_intervalo         (40.0, 50.66]         Total
Enfermedad  relevante
No                         0 (0.0%)    23 (2.44%)
Si                       6 (100.0%)  920 (97.56%)
Total                    6 (100.0%)  943 (100.0%)

IMC_intervalo               (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  \
Infarto agudo al miocardio
No                          12 (29.27%)  123 (38.56%)  145 (36.16%)
Si                          29 (70.73%)  196 (61.44%)  256 (63.84%)
Total                       41 (100.0%)  319 (100.0%)  401 (100.0%)

IMC_intervalo               (29.9, 40.0] (40.0, 50.66]         Total
Infarto agudo al miocardio
No                           70 (37.84%)      0 (0.0%)  351 (36.83%)
Si                          115 (62.16%)    6 (100.0%)  602 (63.17%)
Total                       185 (100.0%)    6 (100.0%)  953 (100.0%)

IMC_intervalo  (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  (29.9, 40.0]  \
ACV
No             37 (90.24%)  286 (89.66%)  356 (88.78%)  169 (91.35%)
Si               4 (9.76%)   33 (10.34%)   45 (11.22%)    16 (8.65%)
Total          41 (100.0%)  319 (100.0%)  401 (100.0%)  185 (100.0%)

IMC_intervalo (40.0, 50.66]         Total
ACV
No               6 (100.0%)  855 (89.72%)
Si                 0 (0.0%)   98 (10.28%)
Total            6 (100.0%)  953 (100.0%)

IMC_intervalo  (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  (29.9, 40.0]  \
Enf Arterial
No             41 (100.0%)  303 (94.98%)  386 (96.26%)  178 (96.22%)
Si                0 (0.0%)    16 (5.02%)    15 (3.74%)     7 (3.78%)
Total          41 (100.0%)  319 (100.0%)  401 (100.0%)  185 (100.0%)

IMC_intervalo (40.0, 50.66]         Total
Enf Arterial
No               6 (100.0%)  915 (96.01%)
Si                 0 (0.0%)    38 (3.99%)
Total            6 (100.0%)  953 (100.0%)

IMC_intervalo     (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  (29.9, 40.0]  \
Angina Inestable
No                41 (100.0%)  316 (99.06%)   393 (98.0%)  181 (97.84%)
Si                   0 (0.0%)     3 (0.94%)      8 (2.0%)     4 (2.16%)
Total             41 (100.0%)  319 (100.0%)  401 (100.0%)  185 (100.0%)

IMC_intervalo    (40.0, 50.66]         Total
Angina Inestable
No                  6 (100.0%)  938 (98.43%)
Si                    0 (0.0%)    15 (1.57%)
Total               6 (100.0%)  953 (100.0%)

IMC_intervalo  (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  (29.9, 40.0]  \
Angina Estble
No             41 (100.0%)  318 (99.69%)  401 (100.0%)  185 (100.0%)
Si                0 (0.0%)     1 (0.31%)      0 (0.0%)      0 (0.0%)
Total          41 (100.0%)  319 (100.0%)  401 (100.0%)  185 (100.0%)

IMC_intervalo (40.0, 50.66]         Total
Angina Estble
No               6 (100.0%)   952 (99.9%)
Si                 0 (0.0%)      1 (0.1%)
Total            6 (100.0%)  953 (100.0%)

IMC_intervalo         (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  (29.9, 40.0]  \
Cateterismo cardiaco
No                     23 (56.1%)  167 (52.35%)   245 (61.1%)  107 (57.84%)
Si                     18 (43.9%)  152 (47.65%)   156 (38.9%)   78 (42.16%)
Total                 41 (100.0%)  319 (100.0%)  401 (100.0%)  185 (100.0%)

IMC_intervalo        (40.0, 50.66]         Total
Cateterismo cardiaco
No                      5 (83.33%)   547 (57.4%)
Si                      1 (16.67%)   406 (42.6%)
Total                   6 (100.0%)  953 (100.0%)

IMC_intervalo                   (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  \
Enfermedad arterial periférica
No                              40 (97.56%)  311 (97.49%)  388 (96.76%)
Si                                1 (2.44%)     8 (2.51%)    13 (3.24%)
Total                           41 (100.0%)  319 (100.0%)  401 (100.0%)

IMC_intervalo                   (29.9, 40.0] (40.0, 50.66]         Total
Enfermedad arterial periférica
No                               180 (97.3%)    6 (100.0%)  926 (97.17%)
Si                                  5 (2.7%)      0 (0.0%)    27 (2.83%)
Total                           185 (100.0%)    6 (100.0%)  953 (100.0%)

IMC_intervalo  (0.0, 19.9]  (19.9, 24.9]  (24.9, 29.9]  (29.9, 40.0]  \
Riesgo CV
Alto              0 (0.0%)    12 (3.76%)      6 (1.5%)    10 (5.41%)
Muy alto       41 (100.0%)  307 (96.24%)   395 (98.5%)  175 (94.59%)
Total          41 (100.0%)  319 (100.0%)  401 (100.0%)  185 (100.0%)

IMC_intervalo (40.0, 50.66]         Total
Riesgo CV
Alto               0 (0.0%)    28 (2.94%)
Muy alto         6 (100.0%)  925 (97.06%)
Total            6 (100.0%)  953 (100.0%)

POC_hba1c_intervalo    (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]    (6.4, 7.5]  \
edad_calculada
25                       1 (0.3%)     0 (0.0%)      0 (0.0%)      0 (0.0%)
31                       1 (0.3%)     0 (0.0%)      0 (0.0%)      0 (0.0%)
33                       0 (0.0%)     0 (0.0%)     1 (0.24%)      0 (0.0%)
34                       1 (0.3%)     0 (0.0%)      0 (0.0%)      0 (0.0%)
35                       1 (0.3%)     0 (0.0%)      0 (0.0%)      0 (0.0%)
...                           ...          ...           ...           ...
90                       0 (0.0%)     0 (0.0%)     1 (0.24%)      0 (0.0%)
91                       1 (0.3%)     0 (0.0%)     2 (0.48%)      0 (0.0%)
92                       0 (0.0%)     0 (0.0%)      0 (0.0%)      0 (0.0%)
93                       0 (0.0%)     0 (0.0%)     1 (0.24%)      0 (0.0%)
Total                330 (100.0%)  19 (100.0%)  420 (100.0%)  119 (100.0%)

POC_hba1c_intervalo  (7.5, 10.0]         Total
edad_calculada
25                      0 (0.0%)      1 (0.1%)
31                      0 (0.0%)      1 (0.1%)
33                      0 (0.0%)      1 (0.1%)
34                      0 (0.0%)      1 (0.1%)
35                      0 (0.0%)      1 (0.1%)
...                          ...           ...
90                      0 (0.0%)      1 (0.1%)
91                      0 (0.0%)     3 (0.31%)
92                     1 (1.79%)      1 (0.1%)
93                      0 (0.0%)      1 (0.1%)
Total                56 (100.0%)  953 (100.0%)

[62 rows x 6 columns]

POC_hba1c_intervalo    (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]    (6.4, 7.5]  \
sexo
femenino              89 (26.97%)   7 (36.84%)   155 (36.9%)   53 (44.54%)
masculino            241 (73.03%)  12 (63.16%)   265 (63.1%)   66 (55.46%)
Total                330 (100.0%)  19 (100.0%)  420 (100.0%)  119 (100.0%)

POC_hba1c_intervalo  (7.5, 10.0]         Total
sexo
femenino             23 (41.07%)  331 (34.73%)
masculino            33 (58.93%)  622 (65.27%)
Total                56 (100.0%)  953 (100.0%)

POC_hba1c_intervalo    (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]    (6.4, 7.5]  \
tipo_de_afiliacion
contributivo         143 (43.33%)   9 (47.37%)  193 (45.95%)   51 (42.86%)
otro                     1 (0.3%)     0 (0.0%)      0 (0.0%)      0 (0.0%)
polizas de seguro        0 (0.0%)     0 (0.0%)     1 (0.24%)      0 (0.0%)
prepagada                1 (0.3%)     0 (0.0%)      0 (0.0%)      0 (0.0%)
regimen especial       24 (7.27%)    1 (5.26%)    23 (5.48%)     4 (3.36%)
subsidiado           161 (48.79%)   9 (47.37%)  203 (48.33%)   64 (53.78%)
Total                330 (100.0%)  19 (100.0%)  420 (100.0%)  119 (100.0%)

POC_hba1c_intervalo  (7.5, 10.0]         Total
tipo_de_afiliacion
contributivo         27 (48.21%)  428 (44.91%)
otro                    0 (0.0%)      1 (0.1%)
polizas de seguro       0 (0.0%)      1 (0.1%)
prepagada               0 (0.0%)      1 (0.1%)
regimen especial       5 (8.93%)    57 (5.98%)
subsidiado           24 (42.86%)  465 (48.79%)
Total                56 (100.0%)  953 (100.0%)

POC_hba1c_intervalo      (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]    (6.4, 7.5]  \
estrato_socieconomico
1                       68 (20.61%)   5 (26.32%)   81 (19.29%)   14 (11.76%)
2                      142 (43.03%)   7 (36.84%)  167 (39.76%)   64 (53.78%)
3                       92 (27.88%)   4 (21.05%)  133 (31.67%)   29 (24.37%)
4                        23 (6.97%)   2 (10.53%)    32 (7.62%)     10 (8.4%)
5                         3 (0.91%)     0 (0.0%)     5 (1.19%)     2 (1.68%)
6                         2 (0.61%)    1 (5.26%)     2 (0.48%)      0 (0.0%)
Total                  330 (100.0%)  19 (100.0%)  420 (100.0%)  119 (100.0%)

POC_hba1c_intervalo    (7.5, 10.0]         Total
estrato_socieconomico
1                       9 (16.07%)  178 (18.68%)
2                      24 (42.86%)  409 (42.92%)
3                      15 (26.79%)  274 (28.75%)
4                       8 (14.29%)    76 (7.97%)
5                         0 (0.0%)    10 (1.05%)
6                         0 (0.0%)     6 (0.63%)
Total                  56 (100.0%)  953 (100.0%)

POC_hba1c_intervalo           (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]  \
antecedentes_de_tabaquismo
no                           231 (70.0%)  15 (78.95%)  261 (62.14%)
si                            99 (30.0%)   4 (21.05%)  159 (37.86%)
Total                       330 (100.0%)  19 (100.0%)  420 (100.0%)

POC_hba1c_intervalo           (6.4, 7.5]  (7.5, 10.0]         Total
antecedentes_de_tabaquismo
no                           77 (64.71%)  36 (64.29%)  627 (65.79%)
si                           42 (35.29%)  20 (35.71%)  326 (34.21%)
Total                       119 (100.0%)  56 (100.0%)  953 (100.0%)

POC_hba1c_intervalo                                (0.0, 5.7] (10.0, 16.3]  \
¿resultados_relacionados_a_problemas cardiacos?
no                                               318 (96.36%)  19 (100.0%)
si                                                 12 (3.64%)     0 (0.0%)
Total                                            330 (100.0%)  19 (100.0%)

POC_hba1c_intervalo                                (5.7, 6.4]    (6.4, 7.5]  \
¿resultados_relacionados_a_problemas cardiacos?
no                                               408 (97.14%)  117 (98.32%)
si                                                 12 (2.86%)     2 (1.68%)
Total                                            420 (100.0%)  119 (100.0%)

POC_hba1c_intervalo                              (7.5, 10.0]         Total
¿resultados_relacionados_a_problemas cardiacos?
no                                               55 (98.21%)  925 (97.16%)
si                                                 1 (1.79%)    27 (2.84%)
Total                                            56 (100.0%)  952 (100.0%)

POC_hba1c_intervalo    (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]    (6.4, 7.5]  \
ACV
No                   279 (84.55%)  18 (94.74%)  390 (92.86%)   109 (91.6%)
Si                    51 (15.45%)    1 (5.26%)    30 (7.14%)     10 (8.4%)
Total                330 (100.0%)  19 (100.0%)  420 (100.0%)  119 (100.0%)

POC_hba1c_intervalo  (7.5, 10.0]         Total
ACV
No                   51 (91.07%)  855 (89.72%)
Si                     5 (8.93%)   98 (10.28%)
Total                56 (100.0%)  953 (100.0%)

POC_hba1c_intervalo    (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]    (6.4, 7.5]  \
Diabetico
No                   297 (90.83%)     0 (0.0%)   327 (78.8%)   38 (32.48%)
Si                     30 (9.17%)  19 (100.0%)    88 (21.2%)   79 (67.52%)
Total                327 (100.0%)  19 (100.0%)  415 (100.0%)  117 (100.0%)

POC_hba1c_intervalo  (7.5, 10.0]         Total
Diabetico
No                    8 (14.29%)   679 (72.0%)
Si                   48 (85.71%)   264 (28.0%)
Total                56 (100.0%)  943 (100.0%)

POC_hba1c_intervalo                                  (0.0, 5.7] (10.0, 16.3]  \
Tiempo de DM
Entre 10 y 20 años                                   7 (24.14%)   8 (44.44%)
Mas de 20 años/ Compromiso de órganos por la di...     0 (0.0%)   2 (11.11%)
Menos de 10 años                                    22 (75.86%)   8 (44.44%)
Total                                               29 (100.0%)  18 (100.0%)

POC_hba1c_intervalo                                  (5.7, 6.4]   (6.4, 7.5]  \
Tiempo de DM
Entre 10 y 20 años                                  26 (30.95%)  30 (40.54%)
Mas de 20 años/ Compromiso de órganos por la di...    2 (2.38%)  12 (16.22%)
Menos de 10 años                                    56 (66.67%)  32 (43.24%)
Total                                               84 (100.0%)  74 (100.0%)

POC_hba1c_intervalo                                 (7.5, 10.0]         Total
Tiempo de DM
Entre 10 y 20 años                                  24 (52.17%)   95 (37.85%)
Mas de 20 años/ Compromiso de órganos por la di...   5 (10.87%)    21 (8.37%)
Menos de 10 años                                    17 (36.96%)  135 (53.78%)
Total                                               46 (100.0%)  251 (100.0%)

POC_hba1c_intervalo    (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]    (6.4, 7.5]  \
Hipertensión
No                   114 (34.97%)   4 (21.05%)   98 (23.67%)   19 (16.24%)
Si                   212 (65.03%)  15 (78.95%)  316 (76.33%)   98 (83.76%)
Total                326 (100.0%)  19 (100.0%)  414 (100.0%)  117 (100.0%)

POC_hba1c_intervalo  (7.5, 10.0]         Total
Hipertensión
No                   10 (17.86%)  249 (26.46%)
Si                   46 (82.14%)  692 (73.54%)
Total                56 (100.0%)  941 (100.0%)

POC_hba1c_intervalo             (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]  \
Hipercolesterolemia familiar
No                            240 (73.39%)  11 (57.89%)   260 (62.8%)
Si                             87 (26.61%)   8 (42.11%)   154 (37.2%)
Total                         327 (100.0%)  19 (100.0%)  414 (100.0%)

POC_hba1c_intervalo             (6.4, 7.5]  (7.5, 10.0]         Total
Hipercolesterolemia familiar
No                             76 (64.96%)  41 (73.21%)  636 (67.52%)
Si                             41 (35.04%)  15 (26.79%)  306 (32.48%)
Total                         117 (100.0%)  56 (100.0%)  942 (100.0%)

POC_hba1c_intervalo    (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]    (6.4, 7.5]  \
ERCoDialisis
No                   317 (96.94%)  18 (94.74%)  400 (96.62%)  110 (94.02%)
Si                     10 (3.06%)    1 (5.26%)    14 (3.38%)     7 (5.98%)
Total                327 (100.0%)  19 (100.0%)  414 (100.0%)  117 (100.0%)

POC_hba1c_intervalo  (7.5, 10.0]         Total
ERCoDialisis
No                   51 (91.07%)  905 (96.07%)
Si                     5 (8.93%)    37 (3.93%)
Total                56 (100.0%)  942 (100.0%)

POC_hba1c_intervalo                 (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]  \
Ultimo Rango de Colesterol total
Desconocido                       245 (75.85%)  17 (89.47%)  348 (84.88%)
Menor o igual a 309                   0 (0.0%)     0 (0.0%)      0 (0.0%)
NA                                 74 (22.91%)   2 (10.53%)   53 (12.93%)
≤309mg/dL                            3 (0.93%)     0 (0.0%)      9 (2.2%)
≥310mg/dL                            1 (0.31%)     0 (0.0%)      0 (0.0%)
Total                             323 (100.0%)  19 (100.0%)  410 (100.0%)

POC_hba1c_intervalo                 (6.4, 7.5]  (7.5, 10.0]         Total
Ultimo Rango de Colesterol total
Desconocido                        106 (90.6%)  47 (83.93%)  770 (82.44%)
Menor o igual a 309                  1 (0.85%)     0 (0.0%)     1 (0.11%)
NA                                  10 (8.55%)   8 (14.29%)  148 (15.85%)
≤309mg/dL                             0 (0.0%)    1 (1.79%)     14 (1.5%)
≥310mg/dL                             0 (0.0%)     0 (0.0%)     1 (0.11%)
Total                             117 (100.0%)  56 (100.0%)  934 (100.0%)

POC_hba1c_intervalo      (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]    (6.4, 7.5]  \
Enfermedad  relevante
No                       12 (3.66%)     0 (0.0%)     6 (1.45%)     5 (4.27%)
Si                     316 (96.34%)  19 (100.0%)  408 (98.55%)  112 (95.73%)
Total                  328 (100.0%)  19 (100.0%)  414 (100.0%)  117 (100.0%)

POC_hba1c_intervalo    (7.5, 10.0]         Total
Enfermedad  relevante
No                        0 (0.0%)    23 (2.44%)
Si                     56 (100.0%)  920 (97.56%)
Total                  56 (100.0%)  943 (100.0%)

POC_hba1c_intervalo           (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]  \
Infarto agudo al miocardio
No                          138 (41.82%)   5 (26.32%)  142 (33.81%)
Si                          192 (58.18%)  14 (73.68%)  278 (66.19%)
Total                       330 (100.0%)  19 (100.0%)  420 (100.0%)

POC_hba1c_intervalo           (6.4, 7.5]  (7.5, 10.0]         Total
Infarto agudo al miocardio
No                           42 (35.29%)   21 (37.5%)  351 (36.83%)
Si                           77 (64.71%)   35 (62.5%)  602 (63.17%)
Total                       119 (100.0%)  56 (100.0%)  953 (100.0%)

POC_hba1c_intervalo    (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]    (6.4, 7.5]  \
ACV
No                   279 (84.55%)  18 (94.74%)  390 (92.86%)   109 (91.6%)
Si                    51 (15.45%)    1 (5.26%)    30 (7.14%)     10 (8.4%)
Total                330 (100.0%)  19 (100.0%)  420 (100.0%)  119 (100.0%)

POC_hba1c_intervalo  (7.5, 10.0]         Total
ACV
No                   51 (91.07%)  855 (89.72%)
Si                     5 (8.93%)   98 (10.28%)
Total                56 (100.0%)  953 (100.0%)

POC_hba1c_intervalo    (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]    (6.4, 7.5]  \
Enf Arterial
No                   317 (96.06%)  18 (94.74%)  402 (95.71%)  115 (96.64%)
Si                     13 (3.94%)    1 (5.26%)    18 (4.29%)     4 (3.36%)
Total                330 (100.0%)  19 (100.0%)  420 (100.0%)  119 (100.0%)

POC_hba1c_intervalo  (7.5, 10.0]         Total
Enf Arterial
No                   54 (96.43%)  915 (96.01%)
Si                     2 (3.57%)    38 (3.99%)
Total                56 (100.0%)  953 (100.0%)

POC_hba1c_intervalo    (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]    (6.4, 7.5]  \
Angina Inestable
No                   322 (97.58%)  19 (100.0%)  416 (99.05%)  118 (99.16%)
Si                      8 (2.42%)     0 (0.0%)     4 (0.95%)     1 (0.84%)
Total                330 (100.0%)  19 (100.0%)  420 (100.0%)  119 (100.0%)

POC_hba1c_intervalo  (7.5, 10.0]         Total
Angina Inestable
No                   55 (98.21%)  938 (98.43%)
Si                     1 (1.79%)    15 (1.57%)
Total                56 (100.0%)  953 (100.0%)

POC_hba1c_intervalo    (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]    (6.4, 7.5]  \
Angina Estble
No                   330 (100.0%)  19 (100.0%)  419 (99.76%)  119 (100.0%)
Si                       0 (0.0%)     0 (0.0%)     1 (0.24%)      0 (0.0%)
Total                330 (100.0%)  19 (100.0%)  420 (100.0%)  119 (100.0%)

POC_hba1c_intervalo  (7.5, 10.0]         Total
Angina Estble
No                   56 (100.0%)   952 (99.9%)
Si                      0 (0.0%)      1 (0.1%)
Total                56 (100.0%)  953 (100.0%)

POC_hba1c_intervalo     (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]    (6.4, 7.5]  \
Cateterismo cardiaco
No                    212 (64.24%)   8 (42.11%)   231 (55.0%)   60 (50.42%)
Si                    118 (35.76%)  11 (57.89%)   189 (45.0%)   59 (49.58%)
Total                 330 (100.0%)  19 (100.0%)  420 (100.0%)  119 (100.0%)

POC_hba1c_intervalo   (7.5, 10.0]         Total
Cateterismo cardiaco
No                     28 (50.0%)   547 (57.4%)
Si                     28 (50.0%)   406 (42.6%)
Total                 56 (100.0%)  953 (100.0%)

POC_hba1c_intervalo               (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]  \
Enfermedad arterial periférica
No                              322 (97.58%)  19 (100.0%)   407 (96.9%)
Si                                 8 (2.42%)     0 (0.0%)     13 (3.1%)
Total                           330 (100.0%)  19 (100.0%)  420 (100.0%)

POC_hba1c_intervalo               (6.4, 7.5]  (7.5, 10.0]         Total
Enfermedad arterial periférica
No                              117 (98.32%)  52 (92.86%)  926 (97.17%)
Si                                 2 (1.68%)    4 (7.14%)    27 (2.83%)
Total                           119 (100.0%)  56 (100.0%)  953 (100.0%)

POC_hba1c_intervalo    (0.0, 5.7] (10.0, 16.3]    (5.7, 6.4]    (6.4, 7.5]  \
Riesgo CV
Alto                    6 (1.82%)    1 (5.26%)     13 (3.1%)     7 (5.88%)
Muy alto             324 (98.18%)  18 (94.74%)   407 (96.9%)  112 (94.12%)
Total                330 (100.0%)  19 (100.0%)  420 (100.0%)  119 (100.0%)

POC_hba1c_intervalo  (7.5, 10.0]         Total
Riesgo CV
Alto                   1 (1.79%)    28 (2.94%)
Muy alto             55 (98.21%)  925 (97.06%)
Total                56 (100.0%)  953 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
edad_calculada
25                                 1 (0.2%)       0 (0.0%)      0 (0.0%)
31                                 0 (0.0%)      1 (0.51%)      0 (0.0%)
33                                 1 (0.2%)       0 (0.0%)      0 (0.0%)
34                                 1 (0.2%)       0 (0.0%)      0 (0.0%)
35                                 1 (0.2%)       0 (0.0%)      0 (0.0%)
...                                     ...            ...           ...
90                                 1 (0.2%)       0 (0.0%)      0 (0.0%)
91                                 0 (0.0%)      1 (0.51%)     2 (0.78%)
92                                 1 (0.2%)       0 (0.0%)      0 (0.0%)
93                                 1 (0.2%)       0 (0.0%)      0 (0.0%)
Total                          499 (100.0%)   195 (100.0%)  258 (100.0%)

perimetro_abdominal_intervalo         Total
edad_calculada
25                                 1 (0.1%)
31                                 1 (0.1%)
33                                 1 (0.1%)
34                                 1 (0.1%)
35                                 1 (0.1%)
...                                     ...
90                                 1 (0.1%)
91                                3 (0.31%)
92                                 1 (0.1%)
93                                 1 (0.1%)
Total                          953 (100.0%)

[62 rows x 4 columns]

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
sexo
femenino                       199 (39.88%)    55 (28.21%)   76 (29.46%)
masculino                      300 (60.12%)   140 (71.79%)  182 (70.54%)
Total                          499 (100.0%)   195 (100.0%)  258 (100.0%)

perimetro_abdominal_intervalo         Total
sexo
femenino                       331 (34.73%)
masculino                      622 (65.27%)
Total                          953 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
tipo_de_afiliacion
contributivo                   222 (44.49%)     86 (44.1%)  119 (46.12%)
otro                               1 (0.2%)       0 (0.0%)      0 (0.0%)
polizas de seguro                  1 (0.2%)       0 (0.0%)      0 (0.0%)
prepagada                          0 (0.0%)      1 (0.51%)      0 (0.0%)
regimen especial                 29 (5.81%)     15 (7.69%)    13 (5.04%)
subsidiado                      246 (49.3%)    93 (47.69%)  126 (48.84%)
Total                          499 (100.0%)   195 (100.0%)  258 (100.0%)

perimetro_abdominal_intervalo         Total
tipo_de_afiliacion
contributivo                   428 (44.91%)
otro                               1 (0.1%)
polizas de seguro                  1 (0.1%)
prepagada                          1 (0.1%)
regimen especial                 57 (5.98%)
subsidiado                     465 (48.79%)
Total                          953 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
estrato_socieconomico
1                              100 (20.04%)    38 (19.49%)    40 (15.5%)
2                              208 (41.68%)    88 (45.13%)  112 (43.41%)
3                              139 (27.86%)    50 (25.64%)   85 (32.95%)
4                                44 (8.82%)     16 (8.21%)     16 (6.2%)
5                                  6 (1.2%)      2 (1.03%)     2 (0.78%)
6                                  2 (0.4%)      1 (0.51%)     3 (1.16%)
Total                          499 (100.0%)   195 (100.0%)  258 (100.0%)

perimetro_abdominal_intervalo         Total
estrato_socieconomico
1                              178 (18.68%)
2                              409 (42.92%)
3                              274 (28.75%)
4                                76 (7.97%)
5                                10 (1.05%)
6                                 6 (0.63%)
Total                          953 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
antecedentes_de_tabaquismo
no                             340 (68.14%)    117 (60.0%)   169 (65.5%)
si                             159 (31.86%)     78 (40.0%)    89 (34.5%)
Total                          499 (100.0%)   195 (100.0%)  258 (100.0%)

perimetro_abdominal_intervalo         Total
antecedentes_de_tabaquismo
no                             627 (65.79%)
si                             326 (34.21%)
Total                          953 (100.0%)

perimetro_abdominal_intervalo                     (0.0, 94.0] (102.0, 151.0]  \
¿resultados_relacionados_a_problemas cardiacos?
no                                               483 (96.79%)   188 (96.41%)
si                                                 16 (3.21%)      7 (3.59%)
Total                                            499 (100.0%)   195 (100.0%)

perimetro_abdominal_intervalo                   (94.0, 102.0]         Total
¿resultados_relacionados_a_problemas cardiacos?
no                                               254 (98.45%)  925 (97.16%)
si                                                  4 (1.55%)    27 (2.84%)
Total                                            258 (100.0%)  952 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
ACV
No                             448 (89.78%)   181 (92.82%)  225 (87.21%)
Si                              51 (10.22%)     14 (7.18%)   33 (12.79%)
Total                          499 (100.0%)   195 (100.0%)  258 (100.0%)

perimetro_abdominal_intervalo         Total
ACV
No                             855 (89.72%)
Si                              98 (10.28%)
Total                          953 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
Diabetico
No                             364 (73.83%)   131 (67.53%)  183 (71.76%)
Si                             129 (26.17%)    63 (32.47%)   72 (28.24%)
Total                          493 (100.0%)   194 (100.0%)  255 (100.0%)

perimetro_abdominal_intervalo         Total
Diabetico
No                              679 (72.0%)
Si                              264 (28.0%)
Total                          943 (100.0%)

perimetro_abdominal_intervalo                        (0.0, 94.0]  \
Tiempo de DM
Entre 10 y 20 años                                   44 (35.48%)
Mas de 20 años/ Compromiso de órganos por la di...     7 (5.65%)
Menos de 10 años                                     73 (58.87%)
Total                                               124 (100.0%)

perimetro_abdominal_intervalo                      (102.0, 151.0]  \
Tiempo de DM
Entre 10 y 20 años                                     22 (40.0%)
Mas de 20 años/ Compromiso de órganos por la di...      4 (7.27%)
Menos de 10 años                                      29 (52.73%)
Total                                                 55 (100.0%)

perimetro_abdominal_intervalo                      (94.0, 102.0]         Total
Tiempo de DM
Entre 10 y 20 años                                   29 (40.28%)   95 (37.85%)
Mas de 20 años/ Compromiso de órganos por la di...   10 (13.89%)    21 (8.37%)
Menos de 10 años                                     33 (45.83%)  135 (53.78%)
Total                                                72 (100.0%)  251 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
Hipertensión
No                             138 (28.05%)    41 (21.13%)   70 (27.56%)
Si                             354 (71.95%)   153 (78.87%)  184 (72.44%)
Total                          492 (100.0%)   194 (100.0%)  254 (100.0%)

perimetro_abdominal_intervalo         Total
Hipertensión
No                             249 (26.46%)
Si                             692 (73.54%)
Total                          941 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
Hipercolesterolemia familiar
No                             324 (65.72%)   133 (68.56%)  178 (70.08%)
Si                             169 (34.28%)    61 (31.44%)   76 (29.92%)
Total                          493 (100.0%)   194 (100.0%)  254 (100.0%)

perimetro_abdominal_intervalo         Total
Hipercolesterolemia familiar
No                             636 (67.52%)
Si                             306 (32.48%)
Total                          942 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
ERCoDialisis
No                             474 (96.15%)   186 (95.88%)  244 (96.06%)
Si                               19 (3.85%)      8 (4.12%)    10 (3.94%)
Total                          493 (100.0%)   194 (100.0%)  254 (100.0%)

perimetro_abdominal_intervalo         Total
ERCoDialisis
No                             905 (96.07%)
Si                               37 (3.93%)
Total                          942 (100.0%)

perimetro_abdominal_intervalo      (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
Ultimo Rango de Colesterol total
Desconocido                       408 (83.27%)   158 (82.29%)  203 (80.88%)
Menor o igual a 309                   0 (0.0%)      1 (0.52%)      0 (0.0%)
NA                                  73 (14.9%)    32 (16.67%)   43 (17.13%)
≤309mg/dL                            9 (1.84%)      1 (0.52%)     4 (1.59%)
≥310mg/dL                             0 (0.0%)       0 (0.0%)      1 (0.4%)
Total                             490 (100.0%)   192 (100.0%)  251 (100.0%)

perimetro_abdominal_intervalo            Total
Ultimo Rango de Colesterol total
Desconocido                       770 (82.44%)
Menor o igual a 309                  1 (0.11%)
NA                                148 (15.85%)
≤309mg/dL                            14 (1.5%)
≥310mg/dL                            1 (0.11%)
Total                             934 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
Enfermedad  relevante
No                               13 (2.63%)      4 (2.06%)     6 (2.36%)
Si                             481 (97.37%)   190 (97.94%)  248 (97.64%)
Total                          494 (100.0%)   194 (100.0%)  254 (100.0%)

perimetro_abdominal_intervalo         Total
Enfermedad  relevante
No                               23 (2.44%)
Si                             920 (97.56%)
Total                          943 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
Infarto agudo al miocardio
No                             195 (39.08%)    66 (33.85%)    89 (34.5%)
Si                             304 (60.92%)   129 (66.15%)   169 (65.5%)
Total                          499 (100.0%)   195 (100.0%)  258 (100.0%)

perimetro_abdominal_intervalo         Total
Infarto agudo al miocardio
No                             351 (36.83%)
Si                             602 (63.17%)
Total                          953 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
ACV
No                             448 (89.78%)   181 (92.82%)  225 (87.21%)
Si                              51 (10.22%)     14 (7.18%)   33 (12.79%)
Total                          499 (100.0%)   195 (100.0%)  258 (100.0%)

perimetro_abdominal_intervalo         Total
ACV
No                             855 (89.72%)
Si                              98 (10.28%)
Total                          953 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
Enf Arterial
No                             482 (96.59%)   186 (95.38%)  246 (95.35%)
Si                               17 (3.41%)      9 (4.62%)    12 (4.65%)
Total                          499 (100.0%)   195 (100.0%)  258 (100.0%)

perimetro_abdominal_intervalo         Total
Enf Arterial
No                             915 (96.01%)
Si                               38 (3.99%)
Total                          953 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
Angina Inestable
No                              491 (98.4%)   193 (98.97%)  253 (98.06%)
Si                                 8 (1.6%)      2 (1.03%)     5 (1.94%)
Total                          499 (100.0%)   195 (100.0%)  258 (100.0%)

perimetro_abdominal_intervalo         Total
Angina Inestable
No                             938 (98.43%)
Si                               15 (1.57%)
Total                          953 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
Angina Estble
No                              498 (99.8%)   195 (100.0%)  258 (100.0%)
Si                                 1 (0.2%)       0 (0.0%)      0 (0.0%)
Total                          499 (100.0%)   195 (100.0%)  258 (100.0%)

perimetro_abdominal_intervalo         Total
Angina Estble
No                              952 (99.9%)
Si                                 1 (0.1%)
Total                          953 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
Cateterismo cardiaco
No                             284 (56.91%)   102 (52.31%)   161 (62.4%)
Si                             215 (43.09%)    93 (47.69%)    97 (37.6%)
Total                          499 (100.0%)   195 (100.0%)  258 (100.0%)

perimetro_abdominal_intervalo         Total
Cateterismo cardiaco
No                              547 (57.4%)
Si                              406 (42.6%)
Total                          953 (100.0%)

perimetro_abdominal_intervalo    (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
Enfermedad arterial periférica
No                               489 (98.0%)   189 (96.92%)  247 (95.74%)
Si                                 10 (2.0%)      6 (3.08%)    11 (4.26%)
Total                           499 (100.0%)   195 (100.0%)  258 (100.0%)

perimetro_abdominal_intervalo          Total
Enfermedad arterial periférica
No                              926 (97.17%)
Si                                27 (2.83%)
Total                           953 (100.0%)

perimetro_abdominal_intervalo   (0.0, 94.0] (102.0, 151.0] (94.0, 102.0]  \
Riesgo CV
Alto                              12 (2.4%)      7 (3.59%)     9 (3.49%)
Muy alto                        487 (97.6%)   188 (96.41%)  249 (96.51%)
Total                          499 (100.0%)   195 (100.0%)  258 (100.0%)

perimetro_abdominal_intervalo         Total
Riesgo CV
Alto                             28 (2.94%)
Muy alto                       925 (97.06%)
Total                          953 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
edad_calculada
25                                       1 (0.25%)       0 (0.0%)
31                                       1 (0.25%)       0 (0.0%)
33                                        0 (0.0%)       1 (0.4%)
34                                       1 (0.25%)       0 (0.0%)
35                                       1 (0.25%)       0 (0.0%)
...                                            ...            ...
90                                        0 (0.0%)       1 (0.4%)
91                                        0 (0.0%)       0 (0.0%)
92                                        0 (0.0%)       1 (0.4%)
93                                        0 (0.0%)       1 (0.4%)
Total                                 402 (100.0%)   249 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
edad_calculada
25                                         0 (0.0%)       0 (0.0%)
31                                         0 (0.0%)       0 (0.0%)
33                                         0 (0.0%)       0 (0.0%)
34                                         0 (0.0%)       0 (0.0%)
35                                         0 (0.0%)       0 (0.0%)
...                                             ...            ...
90                                         0 (0.0%)       0 (0.0%)
91                                        1 (0.95%)      2 (1.02%)
92                                         0 (0.0%)       0 (0.0%)
93                                         0 (0.0%)       0 (0.0%)
Total                                  105 (100.0%)   196 (100.0%)

presion_arterial_sistolica_intervalo         Total
edad_calculada
25                                        1 (0.1%)
31                                        1 (0.1%)
33                                        1 (0.1%)
34                                        1 (0.1%)
35                                        1 (0.1%)
...                                            ...
90                                        1 (0.1%)
91                                       3 (0.31%)
92                                        1 (0.1%)
93                                        1 (0.1%)
Total                                 953 (100.0%)

[62 rows x 5 columns]

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
sexo
femenino                              125 (31.09%)    91 (36.55%)
masculino                             277 (68.91%)   158 (63.45%)
Total                                 402 (100.0%)   249 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
sexo
femenino                                 42 (40.0%)    72 (36.73%)
masculino                                63 (60.0%)   124 (63.27%)
Total                                  105 (100.0%)   196 (100.0%)

presion_arterial_sistolica_intervalo         Total
sexo
femenino                              331 (34.73%)
masculino                             622 (65.27%)
Total                                 953 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
tipo_de_afiliacion
contributivo                          184 (45.77%)   111 (44.58%)
otro                                     1 (0.25%)       0 (0.0%)
polizas de seguro                        1 (0.25%)       0 (0.0%)
prepagada                                1 (0.25%)       0 (0.0%)
regimen especial                        26 (6.47%)     15 (6.02%)
subsidiado                            189 (47.01%)    123 (49.4%)
Total                                 402 (100.0%)   249 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
tipo_de_afiliacion
contributivo                            55 (52.38%)    77 (39.29%)
otro                                       0 (0.0%)       0 (0.0%)
polizas de seguro                          0 (0.0%)       0 (0.0%)
prepagada                                  0 (0.0%)       0 (0.0%)
regimen especial                          8 (7.62%)      8 (4.08%)
subsidiado                               42 (40.0%)   111 (56.63%)
Total                                  105 (100.0%)   196 (100.0%)

presion_arterial_sistolica_intervalo         Total
tipo_de_afiliacion
contributivo                          428 (44.91%)
otro                                      1 (0.1%)
polizas de seguro                         1 (0.1%)
prepagada                                 1 (0.1%)
regimen especial                        57 (5.98%)
subsidiado                            465 (48.79%)
Total                                 953 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
estrato_socieconomico
1                                      64 (15.92%)    42 (16.87%)
2                                      164 (40.8%)   118 (47.39%)
3                                     131 (32.59%)    66 (26.51%)
4                                       34 (8.46%)     20 (8.03%)
5                                        5 (1.24%)       2 (0.8%)
6                                         4 (1.0%)       1 (0.4%)
Total                                 402 (100.0%)   249 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
estrato_socieconomico
1                                       29 (27.62%)    43 (21.94%)
2                                       45 (42.86%)    81 (41.33%)
3                                        23 (21.9%)    54 (27.55%)
4                                         7 (6.67%)     15 (7.65%)
5                                          0 (0.0%)      3 (1.53%)
6                                         1 (0.95%)       0 (0.0%)
Total                                  105 (100.0%)   196 (100.0%)

presion_arterial_sistolica_intervalo         Total
estrato_socieconomico
1                                     178 (18.68%)
2                                     409 (42.92%)
3                                     274 (28.75%)
4                                       76 (7.97%)
5                                       10 (1.05%)
6                                        6 (0.63%)
Total                                 953 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
antecedentes_de_tabaquismo
no                                    251 (62.44%)   157 (63.05%)
si                                    151 (37.56%)    92 (36.95%)
Total                                 402 (100.0%)   249 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
antecedentes_de_tabaquismo
no                                      75 (71.43%)   143 (72.96%)
si                                      30 (28.57%)    53 (27.04%)
Total                                  105 (100.0%)   196 (100.0%)

presion_arterial_sistolica_intervalo         Total
antecedentes_de_tabaquismo
no                                    627 (65.79%)
si                                    326 (34.21%)
Total                                 953 (100.0%)

presion_arterial_sistolica_intervalo             (0.0, 120.0] (120.0, 130.0]  \
¿resultados_relacionados_a_problemas cardiacos?
no                                               390 (97.01%)   242 (97.19%)
si                                                 12 (2.99%)      7 (2.81%)
Total                                            402 (100.0%)   249 (100.0%)

presion_arterial_sistolica_intervalo            (130.0, 139.0] (139.0, 198.0]  \
¿resultados_relacionados_a_problemas cardiacos?
no                                                102 (97.14%)   191 (97.45%)
si                                                   3 (2.86%)      5 (2.55%)
Total                                             105 (100.0%)   196 (100.0%)

presion_arterial_sistolica_intervalo                    Total
¿resultados_relacionados_a_problemas cardiacos?
no                                               925 (97.16%)
si                                                 27 (2.84%)
Total                                            952 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
ACV
No                                    366 (91.04%)   222 (89.16%)
Si                                      36 (8.96%)    27 (10.84%)
Total                                 402 (100.0%)   249 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
ACV
No                                      85 (80.95%)   181 (92.35%)
Si                                      20 (19.05%)     15 (7.65%)
Total                                  105 (100.0%)   196 (100.0%)

presion_arterial_sistolica_intervalo         Total
ACV
No                                    855 (89.72%)
Si                                     98 (10.28%)
Total                                 953 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
Diabetico
No                                    287 (72.11%)   168 (68.29%)
Si                                    111 (27.89%)    78 (31.71%)
Total                                 398 (100.0%)   246 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
Diabetico
No                                      81 (77.88%)    142 (73.2%)
Si                                      23 (22.12%)     52 (26.8%)
Total                                  104 (100.0%)   194 (100.0%)

presion_arterial_sistolica_intervalo         Total
Diabetico
No                                     679 (72.0%)
Si                                     264 (28.0%)
Total                                 943 (100.0%)

presion_arterial_sistolica_intervalo                (0.0, 120.0]  \
Tiempo de DM
Entre 10 y 20 años                                   41 (40.59%)
Mas de 20 años/ Compromiso de órganos por la di...     6 (5.94%)
Menos de 10 años                                     54 (53.47%)
Total                                               101 (100.0%)

presion_arterial_sistolica_intervalo               (120.0, 130.0]  \
Tiempo de DM
Entre 10 y 20 años                                     27 (36.0%)
Mas de 20 años/ Compromiso de órganos por la di...     8 (10.67%)
Menos de 10 años                                      40 (53.33%)
Total                                                 75 (100.0%)

presion_arterial_sistolica_intervalo               (130.0, 139.0]  \
Tiempo de DM
Entre 10 y 20 años                                     12 (50.0%)
Mas de 20 años/ Compromiso de órganos por la di...      2 (8.33%)
Menos de 10 años                                      10 (41.67%)
Total                                                 24 (100.0%)

presion_arterial_sistolica_intervalo               (139.0, 198.0]  \
Tiempo de DM
Entre 10 y 20 años                                    15 (29.41%)
Mas de 20 años/ Compromiso de órganos por la di...       5 (9.8%)
Menos de 10 años                                      31 (60.78%)
Total                                                 51 (100.0%)

presion_arterial_sistolica_intervalo                       Total
Tiempo de DM
Entre 10 y 20 años                                   95 (37.85%)
Mas de 20 años/ Compromiso de órganos por la di...    21 (8.37%)
Menos de 10 años                                    135 (53.78%)
Total                                               251 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
Hipertensión
No                                    132 (33.25%)    60 (24.39%)
Si                                    265 (66.75%)   186 (75.61%)
Total                                 397 (100.0%)   246 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
Hipertensión
No                                      26 (25.24%)    31 (15.98%)
Si                                      77 (74.76%)   163 (84.02%)
Total                                  103 (100.0%)   194 (100.0%)

presion_arterial_sistolica_intervalo         Total
Hipertensión
No                                    249 (26.46%)
Si                                    692 (73.54%)
Total                                 941 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
Hipercolesterolemia familiar
No                                    271 (68.09%)   149 (60.57%)
Si                                    127 (31.91%)    97 (39.43%)
Total                                 398 (100.0%)   246 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
Hipercolesterolemia familiar
No                                       79 (76.7%)    136 (70.1%)
Si                                       24 (23.3%)     58 (29.9%)
Total                                  103 (100.0%)   194 (100.0%)

presion_arterial_sistolica_intervalo         Total
Hipercolesterolemia familiar
No                                    636 (67.52%)
Si                                    306 (32.48%)
Total                                 942 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
ERCoDialisis
No                                    382 (95.98%)   235 (95.53%)
Si                                      16 (4.02%)     11 (4.47%)
Total                                 398 (100.0%)   246 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
ERCoDialisis
No                                     100 (97.09%)   187 (96.39%)
Si                                        3 (2.91%)      7 (3.61%)
Total                                  103 (100.0%)   194 (100.0%)

presion_arterial_sistolica_intervalo         Total
ERCoDialisis
No                                    905 (96.07%)
Si                                      37 (3.93%)
Total                                 942 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
Ultimo Rango de Colesterol total
Desconocido                           320 (81.42%)   211 (86.12%)
Menor o igual a 309                       0 (0.0%)       0 (0.0%)
NA                                     67 (17.05%)    31 (12.65%)
≤309mg/dL                                6 (1.53%)      3 (1.22%)
≥310mg/dL                                 0 (0.0%)       0 (0.0%)
Total                                 393 (100.0%)   245 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
Ultimo Rango de Colesterol total
Desconocido                             84 (81.55%)   154 (80.21%)
Menor o igual a 309                        0 (0.0%)      1 (0.52%)
NA                                      16 (15.53%)    34 (17.71%)
≤309mg/dL                                 3 (2.91%)      2 (1.04%)
≥310mg/dL                                  0 (0.0%)      1 (0.52%)
Total                                  103 (100.0%)   192 (100.0%)

presion_arterial_sistolica_intervalo         Total
Ultimo Rango de Colesterol total
Desconocido                           770 (82.44%)
Menor o igual a 309                      1 (0.11%)
NA                                    148 (15.85%)
≤309mg/dL                                14 (1.5%)
≥310mg/dL                                1 (0.11%)
Total                                 934 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
Enfermedad  relevante
No                                      11 (2.76%)      5 (2.02%)
Si                                    387 (97.24%)   242 (97.98%)
Total                                 398 (100.0%)   247 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
Enfermedad  relevante
No                                        1 (0.97%)      6 (3.09%)
Si                                     102 (99.03%)   188 (96.91%)
Total                                  103 (100.0%)   194 (100.0%)

presion_arterial_sistolica_intervalo         Total
Enfermedad  relevante
No                                      23 (2.44%)
Si                                    920 (97.56%)
Total                                 943 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
Infarto agudo al miocardio
No                                    126 (31.34%)    96 (38.55%)
Si                                    276 (68.66%)   153 (61.45%)
Total                                 402 (100.0%)   249 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
Infarto agudo al miocardio
No                                      54 (51.43%)    74 (37.76%)
Si                                      51 (48.57%)   122 (62.24%)
Total                                  105 (100.0%)   196 (100.0%)

presion_arterial_sistolica_intervalo         Total
Infarto agudo al miocardio
No                                    351 (36.83%)
Si                                    602 (63.17%)
Total                                 953 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
ACV
No                                    366 (91.04%)   222 (89.16%)
Si                                      36 (8.96%)    27 (10.84%)
Total                                 402 (100.0%)   249 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
ACV
No                                      85 (80.95%)   181 (92.35%)
Si                                      20 (19.05%)     15 (7.65%)
Total                                  105 (100.0%)   196 (100.0%)

presion_arterial_sistolica_intervalo         Total
ACV
No                                    855 (89.72%)
Si                                     98 (10.28%)
Total                                 953 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
Enf Arterial
No                                    391 (97.26%)   237 (95.18%)
Si                                      11 (2.74%)     12 (4.82%)
Total                                 402 (100.0%)   249 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
Enf Arterial
No                                      98 (93.33%)   188 (95.92%)
Si                                        7 (6.67%)      8 (4.08%)
Total                                  105 (100.0%)   196 (100.0%)

presion_arterial_sistolica_intervalo         Total
Enf Arterial
No                                    915 (96.01%)
Si                                      38 (3.99%)
Total                                 953 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
Angina Inestable
No                                     398 (99.0%)    247 (99.2%)
Si                                        4 (1.0%)       2 (0.8%)
Total                                 402 (100.0%)   249 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
Angina Inestable
No                                     102 (97.14%)   190 (96.94%)
Si                                        3 (2.86%)      6 (3.06%)
Total                                  105 (100.0%)   196 (100.0%)

presion_arterial_sistolica_intervalo         Total
Angina Inestable
No                                    938 (98.43%)
Si                                      15 (1.57%)
Total                                 953 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
Angina Estble
No                                    401 (99.75%)   249 (100.0%)
Si                                       1 (0.25%)       0 (0.0%)
Total                                 402 (100.0%)   249 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
Angina Estble
No                                     105 (100.0%)   196 (100.0%)
Si                                         0 (0.0%)       0 (0.0%)
Total                                  105 (100.0%)   196 (100.0%)

presion_arterial_sistolica_intervalo         Total
Angina Estble
No                                     952 (99.9%)
Si                                        1 (0.1%)
Total                                 953 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
Cateterismo cardiaco
No                                    223 (55.47%)   140 (56.22%)
Si                                    179 (44.53%)   109 (43.78%)
Total                                 402 (100.0%)   249 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
Cateterismo cardiaco
No                                      70 (66.67%)   114 (58.16%)
Si                                      35 (33.33%)    82 (41.84%)
Total                                  105 (100.0%)   196 (100.0%)

presion_arterial_sistolica_intervalo         Total
Cateterismo cardiaco
No                                     547 (57.4%)
Si                                     406 (42.6%)
Total                                 953 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
Enfermedad arterial periférica
No                                    395 (98.26%)   240 (96.39%)
Si                                       7 (1.74%)      9 (3.61%)
Total                                 402 (100.0%)   249 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
Enfermedad arterial periférica
No                                     100 (95.24%)   190 (96.94%)
Si                                        5 (4.76%)      6 (3.06%)
Total                                  105 (100.0%)   196 (100.0%)

presion_arterial_sistolica_intervalo         Total
Enfermedad arterial periférica
No                                    926 (97.17%)
Si                                      27 (2.83%)
Total                                 953 (100.0%)

presion_arterial_sistolica_intervalo  (0.0, 120.0] (120.0, 130.0]  \
Riesgo CV
Alto                                     8 (1.99%)      6 (2.41%)
Muy alto                              394 (98.01%)   243 (97.59%)
Total                                 402 (100.0%)   249 (100.0%)

presion_arterial_sistolica_intervalo (130.0, 139.0] (139.0, 198.0]  \
Riesgo CV
Alto                                      7 (6.67%)      7 (3.57%)
Muy alto                                98 (93.33%)   189 (96.43%)
Total                                  105 (100.0%)   196 (100.0%)

presion_arterial_sistolica_intervalo         Total
Riesgo CV
Alto                                    28 (2.94%)
Muy alto                              925 (97.06%)
Total                                 953 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
edad_calculada
25                                        1 (0.14%)       0 (0.0%)
31                                        1 (0.14%)       0 (0.0%)
33                                         0 (0.0%)       0 (0.0%)
34                                        1 (0.14%)       0 (0.0%)
35                                        1 (0.14%)       0 (0.0%)
...                                             ...            ...
90                                        1 (0.14%)       0 (0.0%)
91                                        2 (0.28%)       0 (0.0%)
92                                        1 (0.14%)       0 (0.0%)
93                                        1 (0.14%)       0 (0.0%)
Total                                  704 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
edad_calculada
25                                         0 (0.0%)      0 (0.0%)
31                                         0 (0.0%)      0 (0.0%)
33                                        1 (0.52%)      0 (0.0%)
34                                         0 (0.0%)      0 (0.0%)
35                                         0 (0.0%)      0 (0.0%)
...                                             ...           ...
90                                         0 (0.0%)      0 (0.0%)
91                                         0 (0.0%)     1 (1.89%)
92                                         0 (0.0%)      0 (0.0%)
93                                         0 (0.0%)      0 (0.0%)
Total                                  194 (100.0%)   53 (100.0%)

presion_arterial_diastolica_intervalo         Total
edad_calculada
25                                         1 (0.1%)
31                                         1 (0.1%)
33                                         1 (0.1%)
34                                         1 (0.1%)
35                                         1 (0.1%)
...                                             ...
90                                         1 (0.1%)
91                                        3 (0.31%)
92                                         1 (0.1%)
93                                         1 (0.1%)
Total                                  953 (100.0%)

[62 rows x 5 columns]

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
sexo
femenino                               256 (36.36%)       0 (0.0%)
masculino                              448 (63.64%)     1 (100.0%)
Total                                  704 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
sexo
femenino                                61 (31.44%)   13 (24.53%)
masculino                              133 (68.56%)   40 (75.47%)
Total                                  194 (100.0%)   53 (100.0%)

presion_arterial_diastolica_intervalo         Total
sexo
femenino                               331 (34.73%)
masculino                              622 (65.27%)
Total                                  953 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
tipo_de_afiliacion
contributivo                           311 (44.18%)       0 (0.0%)
otro                                      1 (0.14%)       0 (0.0%)
polizas de seguro                         1 (0.14%)       0 (0.0%)
prepagada                                 1 (0.14%)       0 (0.0%)
regimen especial                         41 (5.82%)       0 (0.0%)
subsidiado                             349 (49.57%)     1 (100.0%)
Total                                  704 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
tipo_de_afiliacion
contributivo                            89 (45.88%)   27 (50.94%)
otro                                       0 (0.0%)      0 (0.0%)
polizas de seguro                          0 (0.0%)      0 (0.0%)
prepagada                                  0 (0.0%)      0 (0.0%)
regimen especial                          13 (6.7%)     3 (5.66%)
subsidiado                              92 (47.42%)    23 (43.4%)
Total                                  194 (100.0%)   53 (100.0%)

presion_arterial_diastolica_intervalo         Total
tipo_de_afiliacion
contributivo                           428 (44.91%)
otro                                       1 (0.1%)
polizas de seguro                          1 (0.1%)
prepagada                                  1 (0.1%)
regimen especial                         57 (5.98%)
subsidiado                             465 (48.79%)
Total                                  953 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
estrato_socieconomico
1                                      136 (19.32%)       0 (0.0%)
2                                       302 (42.9%)     1 (100.0%)
3                                      201 (28.55%)       0 (0.0%)
4                                        55 (7.81%)       0 (0.0%)
5                                         7 (0.99%)       0 (0.0%)
6                                         3 (0.43%)       0 (0.0%)
Total                                  704 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
estrato_socieconomico
1                                       31 (15.98%)   11 (20.75%)
2                                       79 (40.72%)   26 (49.06%)
3                                       62 (31.96%)   11 (20.75%)
4                                        17 (8.76%)     4 (7.55%)
5                                         2 (1.03%)     1 (1.89%)
6                                         3 (1.55%)      0 (0.0%)
Total                                  194 (100.0%)   53 (100.0%)

presion_arterial_diastolica_intervalo         Total
estrato_socieconomico
1                                      178 (18.68%)
2                                      409 (42.92%)
3                                      274 (28.75%)
4                                        76 (7.97%)
5                                        10 (1.05%)
6                                         6 (0.63%)
Total                                  953 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
antecedentes_de_tabaquismo
no                                     445 (63.21%)     1 (100.0%)
si                                     259 (36.79%)       0 (0.0%)
Total                                  704 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
antecedentes_de_tabaquismo
no                                     139 (71.65%)   41 (77.36%)
si                                      55 (28.35%)   12 (22.64%)
Total                                  194 (100.0%)   53 (100.0%)

presion_arterial_diastolica_intervalo         Total
antecedentes_de_tabaquismo
no                                     627 (65.79%)
si                                     326 (34.21%)
Total                                  953 (100.0%)

presion_arterial_diastolica_intervalo             (0.0, 80.0] (120.0, 129.0]  \
¿resultados_relacionados_a_problemas cardiacos?
no                                               684 (97.16%)     1 (100.0%)
si                                                 20 (2.84%)       0 (0.0%)
Total                                            704 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo            (80.0, 90.0] (90.0, 120.0]  \
¿resultados_relacionados_a_problemas cardiacos?
no                                               189 (97.42%)   51 (96.23%)
si                                                  5 (2.58%)     2 (3.77%)
Total                                            194 (100.0%)   53 (100.0%)

presion_arterial_diastolica_intervalo                   Total
¿resultados_relacionados_a_problemas cardiacos?
no                                               925 (97.16%)
si                                                 27 (2.84%)
Total                                            952 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
ACV
No                                     639 (90.77%)     1 (100.0%)
Si                                       65 (9.23%)       0 (0.0%)
Total                                  704 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
ACV
No                                     166 (85.57%)   48 (90.57%)
Si                                      28 (14.43%)     5 (9.43%)
Total                                  194 (100.0%)   53 (100.0%)

presion_arterial_diastolica_intervalo         Total
ACV
No                                     855 (89.72%)
Si                                      98 (10.28%)
Total                                  953 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
Diabetico
No                                     486 (69.73%)     1 (100.0%)
Si                                     211 (30.27%)       0 (0.0%)
Total                                  697 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
Diabetico
No                                     151 (78.65%)   40 (76.92%)
Si                                      41 (21.35%)   12 (23.08%)
Total                                  192 (100.0%)   52 (100.0%)

presion_arterial_diastolica_intervalo         Total
Diabetico
No                                      679 (72.0%)
Si                                      264 (28.0%)
Total                                  943 (100.0%)

presion_arterial_diastolica_intervalo                (0.0, 80.0] (80.0, 90.0]  \
Tiempo de DM
Entre 10 y 20 años                                    79 (40.1%)  14 (32.56%)
Mas de 20 años/ Compromiso de órganos por la di...    17 (8.63%)     4 (9.3%)
Menos de 10 años                                    101 (51.27%)  25 (58.14%)
Total                                               197 (100.0%)  43 (100.0%)

presion_arterial_diastolica_intervalo              (90.0, 120.0]         Total
Tiempo de DM
Entre 10 y 20 años                                    2 (18.18%)   95 (37.85%)
Mas de 20 años/ Compromiso de órganos por la di...      0 (0.0%)    21 (8.37%)
Menos de 10 años                                      9 (81.82%)  135 (53.78%)
Total                                                11 (100.0%)  251 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
Hipertensión
No                                     193 (27.77%)       0 (0.0%)
Si                                     502 (72.23%)     1 (100.0%)
Total                                  695 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
Hipertensión
No                                      45 (23.44%)   11 (21.15%)
Si                                     147 (76.56%)   41 (78.85%)
Total                                  192 (100.0%)   52 (100.0%)

presion_arterial_diastolica_intervalo         Total
Hipertensión
No                                     249 (26.46%)
Si                                     692 (73.54%)
Total                                  941 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
Hipercolesterolemia familiar
No                                     453 (65.09%)     1 (100.0%)
Si                                     243 (34.91%)       0 (0.0%)
Total                                  696 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
Hipercolesterolemia familiar
No                                     140 (72.92%)   41 (78.85%)
Si                                      52 (27.08%)   11 (21.15%)
Total                                  192 (100.0%)   52 (100.0%)

presion_arterial_diastolica_intervalo         Total
Hipercolesterolemia familiar
No                                     636 (67.52%)
Si                                     306 (32.48%)
Total                                  942 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
ERCoDialisis
No                                     671 (96.41%)     1 (100.0%)
Si                                       25 (3.59%)       0 (0.0%)
Total                                  696 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
ERCoDialisis
No                                     181 (94.27%)   51 (98.08%)
Si                                       11 (5.73%)     1 (1.92%)
Total                                  192 (100.0%)   52 (100.0%)

presion_arterial_diastolica_intervalo         Total
ERCoDialisis
No                                     905 (96.07%)
Si                                       37 (3.93%)
Total                                  942 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
Ultimo Rango de Colesterol total
Desconocido                            567 (82.17%)       0 (0.0%)
Menor o igual a 309                        0 (0.0%)       0 (0.0%)
NA                                     112 (16.23%)     1 (100.0%)
≤309mg/dL                                11 (1.59%)       0 (0.0%)
≥310mg/dL                                  0 (0.0%)       0 (0.0%)
Total                                  690 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
Ultimo Rango de Colesterol total
Desconocido                            167 (87.43%)   35 (68.63%)
Menor o igual a 309                       1 (0.52%)      0 (0.0%)
NA                                      21 (10.99%)   14 (27.45%)
≤309mg/dL                                 2 (1.05%)     1 (1.96%)
≥310mg/dL                                  0 (0.0%)     1 (1.96%)
Total                                  191 (100.0%)   51 (100.0%)

presion_arterial_diastolica_intervalo         Total
Ultimo Rango de Colesterol total
Desconocido                            770 (82.44%)
Menor o igual a 309                       1 (0.11%)
NA                                     148 (15.85%)
≤309mg/dL                                 14 (1.5%)
≥310mg/dL                                 1 (0.11%)
Total                                  934 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
Enfermedad  relevante
No                                       15 (2.16%)       0 (0.0%)
Si                                     681 (97.84%)     1 (100.0%)
Total                                  696 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
Enfermedad  relevante
No                                        6 (3.11%)     2 (3.85%)
Si                                     187 (96.89%)   50 (96.15%)
Total                                  193 (100.0%)   52 (100.0%)

presion_arterial_diastolica_intervalo         Total
Enfermedad  relevante
No                                       23 (2.44%)
Si                                     920 (97.56%)
Total                                  943 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
Infarto agudo al miocardio
No                                     244 (34.66%)       0 (0.0%)
Si                                     460 (65.34%)     1 (100.0%)
Total                                  704 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
Infarto agudo al miocardio
No                                      85 (43.81%)   21 (39.62%)
Si                                     109 (56.19%)   32 (60.38%)
Total                                  194 (100.0%)   53 (100.0%)

presion_arterial_diastolica_intervalo         Total
Infarto agudo al miocardio
No                                     351 (36.83%)
Si                                     602 (63.17%)
Total                                  953 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
ACV
No                                     639 (90.77%)     1 (100.0%)
Si                                       65 (9.23%)       0 (0.0%)
Total                                  704 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
ACV
No                                     166 (85.57%)   48 (90.57%)
Si                                      28 (14.43%)     5 (9.43%)
Total                                  194 (100.0%)   53 (100.0%)

presion_arterial_diastolica_intervalo         Total
ACV
No                                     855 (89.72%)
Si                                      98 (10.28%)
Total                                  953 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
Enf Arterial
No                                     680 (96.59%)     1 (100.0%)
Si                                       24 (3.41%)       0 (0.0%)
Total                                  704 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
Enf Arterial
No                                      181 (93.3%)   52 (98.11%)
Si                                        13 (6.7%)     1 (1.89%)
Total                                  194 (100.0%)   53 (100.0%)

presion_arterial_diastolica_intervalo         Total
Enf Arterial
No                                     915 (96.01%)
Si                                       38 (3.99%)
Total                                  953 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
Angina Inestable
No                                     694 (98.58%)     1 (100.0%)
Si                                       10 (1.42%)       0 (0.0%)
Total                                  704 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
Angina Inestable
No                                     192 (98.97%)   50 (94.34%)
Si                                        2 (1.03%)     3 (5.66%)
Total                                  194 (100.0%)   53 (100.0%)

presion_arterial_diastolica_intervalo         Total
Angina Inestable
No                                     938 (98.43%)
Si                                       15 (1.57%)
Total                                  953 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
Angina Estble
No                                     703 (99.86%)     1 (100.0%)
Si                                        1 (0.14%)       0 (0.0%)
Total                                  704 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
Angina Estble
No                                     194 (100.0%)   53 (100.0%)
Si                                         0 (0.0%)      0 (0.0%)
Total                                  194 (100.0%)   53 (100.0%)

presion_arterial_diastolica_intervalo         Total
Angina Estble
No                                      952 (99.9%)
Si                                         1 (0.1%)
Total                                  953 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
Cateterismo cardiaco
No                                     375 (53.27%)     1 (100.0%)
Si                                     329 (46.73%)       0 (0.0%)
Total                                  704 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
Cateterismo cardiaco
No                                     132 (68.04%)   39 (73.58%)
Si                                      62 (31.96%)   14 (26.42%)
Total                                  194 (100.0%)   53 (100.0%)

presion_arterial_diastolica_intervalo         Total
Cateterismo cardiaco
No                                      547 (57.4%)
Si                                      406 (42.6%)
Total                                  953 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
Enfermedad arterial periférica
No                                     688 (97.73%)     1 (100.0%)
Si                                       16 (2.27%)       0 (0.0%)
Total                                  704 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
Enfermedad arterial periférica
No                                     183 (94.33%)   53 (100.0%)
Si                                       11 (5.67%)      0 (0.0%)
Total                                  194 (100.0%)   53 (100.0%)

presion_arterial_diastolica_intervalo         Total
Enfermedad arterial periférica
No                                     926 (97.17%)
Si                                       27 (2.83%)
Total                                  953 (100.0%)

presion_arterial_diastolica_intervalo   (0.0, 80.0] (120.0, 129.0]  \
Riesgo CV
Alto                                     18 (2.56%)       0 (0.0%)
Muy alto                               686 (97.44%)     1 (100.0%)
Total                                  704 (100.0%)     1 (100.0%)

presion_arterial_diastolica_intervalo  (80.0, 90.0] (90.0, 120.0]  \
Riesgo CV
Alto                                      7 (3.61%)     3 (5.66%)
Muy alto                               187 (96.39%)   50 (94.34%)
Total                                  194 (100.0%)   53 (100.0%)

presion_arterial_diastolica_intervalo         Total
Riesgo CV
Alto                                     28 (2.94%)
Muy alto                               925 (97.06%)
Total                                  953 (100.0%)

In [28]:
'hb1ac_controlado' in list(df.columns)

False

In [32]:
'hb1ac_controlado' in df.columns

True

In [42]:
import pandas as pd
import plotly.graph_objects as go

# Variables que deseas analizar
variables = ['hb1ac_controlado', 'peso_controlado', 'tension_controlada', 'perimtero_abdominal_controlado']

# Crear tabla de conteo y porcentaje para cada variable
summary = []
for col in variables:
    if col in df.columns:
        # Calcular conteo y porcentaje
        conteo = df[col].value_counts().reset_index()
        conteo.columns = ['Respuesta', 'Conteo']
        porcentaje = df[col].value_counts(normalize=True).mul(100).reset_index()
        porcentaje.columns = ['Respuesta', 'Porcentaje']
        
        # Combinar conteo y porcentaje
        tabla = pd.merge(conteo, porcentaje, on='Respuesta')
        tabla['Variable'] = col
        summary.append(tabla)

# Combinar resultados en un único DataFrame
final_summary = pd.concat(summary, ignore_index=True)
out_sum = pd.DataFrame()
out_sum['Variable'] =  final_summary["Variable"]
out_sum["Respuesta"] =  final_summary["Respuesta"]
out_sum["Conteo"] =  final_summary["Conteo"]
out_sum["Porcentaje"] =  final_summary["Porcentaje"]
print(out_sum)
fig = go.Figure(
    data=[
        go.Table(
            header=dict(
                values=["Variable", "Respuesta", "Conteo", "Porcentaje (%)"],
                fill_color="lightgrey",
                align="left"
            ),
            cells=dict(
                values=[
                    final_summary["Variable"],
                    final_summary["Respuesta"],
                    final_summary["Conteo"],
                    (final_summary["Porcentaje"])
                ],
                fill_color="white",
                align="left"
            )
        )
    ]
)

# Mostrar la tabla
fig.show()

                         Variable      Respuesta  Conteo  Porcentaje
0                hb1ac_controlado  no controlado     687   72.088143
1                hb1ac_controlado     controlado     266   27.911857
2                 peso_controlado  no controlado     626   65.687303
3                 peso_controlado     controlado     327   34.312697
4              tension_controlada     controlado     819   85.939140
5              tension_controlada  no controlado     134   14.060860
6  perimtero_abdominal_controlado  no controlado     628   65.897167
7  perimtero_abdominal_controlado     controlado     325   34.102833

In [49]:
import pandas as pd
import plotly.express as px

# Variables base y variables a cruzar
variables_base =['hb1ac_controlado', 'peso_controlado', 'tension_controlada', 'perimtero_abdominal_controlado']
variables_cruce = ['Hipolipemiante', 
                   'cLDL_controlado', 
                   'antecedentes_de_tabaquismo', 
                   '¿resultados_relacionados_a_problemas cardiacos?', 
                   'HDL_controlado', 
                   'Trigliceridos_controlados']

# Generar tablas de frecuencias cruzadas con gráficas
for base_var in variables_base:
    for cross_var in variables_cruce:
        if base_var in df.columns and cross_var in df.columns:
            # Crear tabla cruzada
            cross_tab = pd.crosstab(df[base_var], df[cross_var], normalize='index') * 100
            cross_tab = cross_tab.round(2).reset_index()

            # Transformar tabla cruzada a formato largo para graficar
            cross_tab_long = cross_tab.melt(id_vars=[base_var], var_name=cross_var, value_name='Porcentaje')

            # Crear gráfico de barras apiladas
            fig = px.bar(
                cross_tab_long,
                x=base_var,
                y='Porcentaje',
                color=cross_var,
                title=f"Frecuencias Cruzadas: {base_var} \n vs {cross_var}",
                labels={base_var: base_var, cross_var: "Categoría", 'Porcentaje': 'Porcentaje (%)'},
                text='Porcentaje'
            )

            # Cambiar ancho de la gráfica
            fig.update_layout(
                barmode='stack', 
                xaxis={'categoryorder': 'total ascending'},
                width=1200  # Ajusta el ancho aquí (en píxeles)
            )
            fig.show()

## Colesterol_total_controlado

In [15]:
agrupaciones =['edad_calculada',
 'sexo',
 'tipo_de_afiliacion',
 'estrato_socieconomico',
 'antecedentes_de_tabaquismo',
 '¿resultados_relacionados_a_problemas cardiacos?',
 'ACV',
 'Riesgo CV']
variables = ['colesterol_total_controlado']

In [14]:
import pandas as pd
from scipy.stats import chi2_contingency
import plotly.graph_objects as go

# Definir intervalos y etiquetas para agrupar edades
edad_intervals = [0, 49, 59, 79, 150]
edad_labels = ['<50', '50-59', '60-79', '>80']
variables_categoricas = ['edad_grupo', 'sexo']+['Hipolipemiante']+ ['cLDL_controlado',
                                                                    'estrato_socieconomico',
 'antecedentes_de_tabaquismo',
 '¿resultados_relacionados_a_problemas cardiacos?',
       'HDL_controlado',
       'Trigliceridos_controlados']
variables_numericas = ['edad_calculada'] 

# Creación de grupo por intervalos de edad
df['edad_grupo'] = pd.cut(
    df['edad_calculada'], bins=edad_intervals, labels=edad_labels, right=False
)

for variable in variables:
    for agrupacion in agrupaciones:
        # Crear tabla de frecuencias cruzadas con totales incluidos
        if agrupacion == 'edad_calculada':
            # Usar 'edad_grupo' directamente
            tabla_frecuencias = pd.crosstab(
                df['edad_grupo'], df[variable], margins=True, margins_name="Total"
            )
        else:
            tabla_frecuencias = pd.crosstab(
                df[agrupacion], df[variable], margins=True, margins_name="Total"
            )
        
        # Reordenar las columnas en el orden 'si', 'no', 'Total'
        if 'si' in tabla_frecuencias.columns and 'no' in tabla_frecuencias.columns:
            tabla_frecuencias = tabla_frecuencias[['si', 'no', 'Total']]
        
        # Calcular porcentajes por columnas
        totales_columna = tabla_frecuencias.loc["Total", :]
        porcentajes = (tabla_frecuencias.div(totales_columna, axis=1) * 100).round(2)
        
        # Combinar frecuencias y porcentajes en un formato "valor (porcentaje%)"
        tabla_final_percent = tabla_frecuencias.astype(str) + " (" + porcentajes.astype(str) + "%)"
        
        # Crear título dinámico para la esquina superior izquierda
        titulo_esquina = f"{agrupacion}/{variable}"

        # Verificar si es una combinación de variables categóricas
        if agrupacion in variables_categoricas and variable in variables_categoricas:
            print(agrupacion, variable)
            
            tabla_frecuencias = pd.crosstab(
                df[agrupacion], df[variable]
            )
            if tabla_frecuencias.shape[0] > 1 and tabla_frecuencias.shape[1] > 1:
                try:
                    chi2, p, dof, expected = chi2_contingency(tabla_frecuencias)
                    print(f"Chi-cuadrado entre {agrupacion} y {variable}:")
                    print(f"  Estadístico Chi2: {chi2:.2f}")
                    print(f"  p-valor: {p:.4f}")
                    print(f"  Grados de libertad: {dof}")
                except ValueError:
                    print(f"No se puede calcular Chi-cuadrado entre {agrupacion} y {variable}: tabla inválida.")
            else:
                print(f"La tabla de contingencia para {agrupacion} y {variable} no tiene suficientes datos.")
        elif agrupacion in variables_numericas or variable in variables_numericas:
            print(f"Variables numéricas detectadas: {agrupacion} y/o {variable}.")
            if df[agrupacion].dtype == 'object' and df[agrupacion].isin(['si', 'no']).any():
                df[agrupacion] = df[agrupacion].replace({'si': 1, 'no': 0})
            if df[variable].dtype == 'object' and df[variable].isin(['si', 'no']).any():
                df[variable] = df[variable].replace({'si': 1, 'no': 0})
            if df[agrupacion].dtype in ['int64', 'float64'] and df[variable].dtype in ['int64', 'float64']:
                correlacion = df[agrupacion].corr(df[variable])
                print(f"  Correlación de Pearson: {correlacion:.2f}")
            else:
                print(f"Una o ambas variables no son numéricas para calcular la correlación.")
            if df[agrupacion].isin([1, 0]).any():
                df[agrupacion] = df[agrupacion].replace({1: 'si', 0: 'no'})
            
            if df[variable].isin([0, 1]).any():
                df[variable] = df[variable].replace({1: 'si', 0: 'no'})
        print(tabla_final_percent)
        display(tabla_final_percent)

Variables numéricas detectadas: edad_calculada y/o colesterol_total_controlado.
Una o ambas variables no son numéricas para calcular la correlación.
colesterol_total_controlado    controlado no controlado         Total
edad_grupo
<50                            33 (4.55%)     13 (5.7%)    46 (4.83%)
50-59                        105 (14.48%)   40 (17.54%)  145 (15.22%)
60-79                        483 (66.62%)  157 (68.86%)  640 (67.16%)
>80                          104 (14.34%)    18 (7.89%)   122 (12.8%)
Total                        725 (100.0%)  228 (100.0%)  953 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
edad_grupo
<50                            33 (4.55%)     13 (5.7%)    46 (4.83%)
50-59                        105 (14.48%)   40 (17.54%)  145 (15.22%)
60-79                        483 (66.62%)  157 (68.86%)  640 (67.16%)
>80                          104 (14.34%)    18 (7.89%)   122 (12.8%)
Total                        725 (100.0%)  228 (100.0%)  953 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
sexo
femenino                     221 (30.48%)  110 (48.25%)  331 (34.73%)
masculino                    504 (69.52%)  118 (51.75%)  622 (65.27%)
Total                        725 (100.0%)  228 (100.0%)  953 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
sexo
femenino                     221 (30.48%)  110 (48.25%)  331 (34.73%)
masculino                    504 (69.52%)  118 (51.75%)  622 (65.27%)
Total                        725 (100.0%)  228 (100.0%)  953 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
tipo_de_afiliacion
contributivo                 334 (46.07%)   94 (41.23%)  428 (44.91%)
otro                            1 (0.14%)      0 (0.0%)      1 (0.1%)
polizas de seguro               1 (0.14%)      0 (0.0%)      1 (0.1%)
prepagada                       1 (0.14%)      0 (0.0%)      1 (0.1%)
regimen especial               44 (6.07%)     13 (5.7%)    57 (5.98%)
subsidiado                   344 (47.45%)  121 (53.07%)  465 (48.79%)
Total                        725 (100.0%)  228 (100.0%)  953 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
tipo_de_afiliacion
contributivo                 334 (46.07%)   94 (41.23%)  428 (44.91%)
otro                            1 (0.14%)      0 (0.0%)      1 (0.1%)
polizas de seguro               1 (0.14%)      0 (0.0%)      1 (0.1%)
prepagada                       1 (0.14%)      0 (0.0%)      1 (0.1%)
regimen especial               44 (6.07%)     13 (5.7%)    57 (5.98%)
subsidiado                   344 (47.45%)  121 (53.07%)  465 (48.79%)
Total                        725 (100.0%)  228 (100.0%)  953 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
estrato_socieconomico
1                            133 (18.34%)   45 (19.74%)  178 (18.68%)
2                            315 (43.45%)   94 (41.23%)  409 (42.92%)
3                            200 (27.59%)   74 (32.46%)  274 (28.75%)
4                              63 (8.69%)     13 (5.7%)    76 (7.97%)
5                              10 (1.38%)      0 (0.0%)    10 (1.05%)
6                               4 (0.55%)     2 (0.88%)     6 (0.63%)
Total                        725 (100.0%)  228 (100.0%)  953 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
estrato_socieconomico
1                            133 (18.34%)   45 (19.74%)  178 (18.68%)
2                            315 (43.45%)   94 (41.23%)  409 (42.92%)
3                            200 (27.59%)   74 (32.46%)  274 (28.75%)
4                              63 (8.69%)     13 (5.7%)    76 (7.97%)
5                              10 (1.38%)      0 (0.0%)    10 (1.05%)
6                               4 (0.55%)     2 (0.88%)     6 (0.63%)
Total                        725 (100.0%)  228 (100.0%)  953 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
antecedentes_de_tabaquismo
no                           457 (63.03%)  170 (74.56%)  627 (65.79%)
si                           268 (36.97%)   58 (25.44%)  326 (34.21%)
Total                        725 (100.0%)  228 (100.0%)  953 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
antecedentes_de_tabaquismo
no                           457 (63.03%)  170 (74.56%)  627 (65.79%)
si                           268 (36.97%)   58 (25.44%)  326 (34.21%)
Total                        725 (100.0%)  228 (100.0%)  953 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
ACV
No                           645 (88.97%)  210 (92.11%)  855 (89.72%)
Si                            80 (11.03%)    18 (7.89%)   98 (10.28%)
Total                        725 (100.0%)  228 (100.0%)  953 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
ACV
No                           645 (88.97%)  210 (92.11%)  855 (89.72%)
Si                            80 (11.03%)    18 (7.89%)   98 (10.28%)
Total                        725 (100.0%)  228 (100.0%)  953 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
Enfermedad  relevante
No                              18 (2.5%)     5 (2.24%)    23 (2.44%)
Si                            702 (97.5%)  218 (97.76%)  920 (97.56%)
Total                        720 (100.0%)  223 (100.0%)  943 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
Enfermedad  relevante
No                              18 (2.5%)     5 (2.24%)    23 (2.44%)
Si                            702 (97.5%)  218 (97.76%)  920 (97.56%)
Total                        720 (100.0%)  223 (100.0%)  943 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
ACV
No                           645 (88.97%)  210 (92.11%)  855 (89.72%)
Si                            80 (11.03%)    18 (7.89%)   98 (10.28%)
Total                        725 (100.0%)  228 (100.0%)  953 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
ACV
No                           645 (88.97%)  210 (92.11%)  855 (89.72%)
Si                            80 (11.03%)    18 (7.89%)   98 (10.28%)
Total                        725 (100.0%)  228 (100.0%)  953 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
Riesgo CV
Alto                            21 (2.9%)     7 (3.07%)    28 (2.94%)
Muy alto                      704 (97.1%)  221 (96.93%)  925 (97.06%)
Total                        725 (100.0%)  228 (100.0%)  953 (100.0%)

colesterol_total_controlado    controlado no controlado         Total
Riesgo CV
Alto                            21 (2.9%)     7 (3.07%)    28 (2.94%)
Muy alto                      704 (97.1%)  221 (96.93%)  925 (97.06%)
Total                        725 (100.0%)  228 (100.0%)  953 (100.0%)

In [10]:
import pandas as pd
import plotly.express as px

# Variables base y variables a cruzar
variables_base =['hb1ac_controlado', 'Hipolipemiante','¿resultados_relacionados_a_problemas cardiacos?','antecedentes_de_tabaquismo', 'peso_controlado', 'tension_controlada', 'perimtero_abdominal_controlado']
variables_cruce = ['colesterol_total_controlado']

# Generar tablas de frecuencias cruzadas con gráficas
for base_var in variables_base:
    for cross_var in variables_cruce:
        if base_var in df.columns and cross_var in df.columns:
            # Crear tabla cruzada
            cross_tab = pd.crosstab(df[base_var], df[cross_var], normalize='index') * 100
            cross_tab = cross_tab.round(2).reset_index()

            # Transformar tabla cruzada a formato largo para graficar
            cross_tab_long = cross_tab.melt(id_vars=[base_var], var_name=cross_var, value_name='Porcentaje')

            # Crear gráfico de barras apiladas
            fig = px.bar(
                cross_tab_long,
                x=base_var,
                y='Porcentaje',
                color=cross_var,
                title=f"Frecuencias Cruzadas: {base_var} \n vs {cross_var}",
                labels={base_var: base_var, cross_var: "Categoría", 'Porcentaje': 'Porcentaje (%)'},
                text='Porcentaje'
            )

            # Cambiar ancho de la gráfica
            fig.update_layout(
                barmode='stack', 
                xaxis={'categoryorder': 'total ascending'},
                width=1200  # Ajusta el ancho aquí (en píxeles)
            )
            fig.show()

In [12]:
df['estrato_socieconomico']

0      6
1      3
2      4
3      4
4      6
      ..
948    2
949    2
950    3
951    4
952    3
Name: estrato_socieconomico, Length: 953, dtype: int64